version: "3.8"
services:
  resumebuilder-frontend:
    image: registry.aperasoftwares.com/aperra-org/resumebuilder-frontend:latest
    container_name: resumebuilder-frontend-latest
    restart: unless-stopped
    ports:
      - "8093:8093"
    environment:
      - NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    networks:
      - resumebuilder-network

networks:
  resumebuilder-network:
    name: resumebuilder-network
    external: true
