// src/candidate/candidate.service.ts
import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma.service';
import { CandidateDto } from 'src/Validations/candidate/create-candidate.dto';
import { join } from 'path';
import { extname } from 'path';
import { NotFoundException } from '@nestjs/common';
import * as fs from 'fs';
import { PDFParse } from 'pdf-parse';
import * as mammoth from 'mammoth';
import { Document, Packer, Paragraph, TextRun } from 'docx';
import * as libre from 'libreoffice-convert';
import { promisify } from 'util';

import { EventEmitter2 } from '@nestjs/event-emitter';
import { CandidateCreatedEvent } from 'src/envent/events';

@Injectable()
export class CandidateService {
  constructor(
    private prisma: PrismaService,
    private eventEmitter: EventEmitter2,
  ) {}

  async uploadFileMulter(
    file: Express.Multer.File,
    candidateData: CandidateDto,
  ): Promise<any> {
    console.log('File ', file);

    const allowedExtensions = ['.pdf', '.doc', '.docx'];
    const fileExtension = extname(file.originalname);

    if (!allowedExtensions.includes(fileExtension)) {
      throw new Error(
        'Invalid file type. Only PDF and Word documents are allowed.',
      );
    }

    // Use the filename generated by Multer's diskStorage configuration
    const uniqueFileName = file.filename;

    const yearsOfExperience = Number(candidateData.yearsOfExperience);
    const noticePeriod = Number(candidateData.noticePeriod);

    let skillsArray: string[] = [];

    if (candidateData.skills) {
      if (typeof candidateData.skills === 'string') {
        skillsArray = candidateData.skills.split(',').map((s) => s.trim());
      } else if (Array.isArray(candidateData.skills)) {
        skillsArray = candidateData.skills.map((s) => s.trim());
      }
    }

    // Check if candidate with this email already exists to avoid unique constraint violations
    const existingCandidate = await this.prisma.candidate.findUnique({
      where: { email: candidateData.email },
    });

    if (existingCandidate) {
      // Delete old resume file if it exists and is different from the newly uploaded one
      if (existingCandidate.resume && existingCandidate.resume !== file.filename) {
        const oldFilePath = join(process.cwd(), 'uploads', existingCandidate.resume);
        try {
          if (fs.existsSync(oldFilePath)) {
            fs.unlinkSync(oldFilePath);
          }
        } catch (err) {
          console.error(`Error deleting old resume file: ${existingCandidate.resume}`, err);
        }
      }

      // Update candidate record
      const updatedCandidate = await this.prisma.candidate.update({
        where: { id: existingCandidate.id },
        data: {
          firstName: candidateData.firstName,
          lastName: candidateData.lastName,
          mobile: candidateData.mobile,
          yearsOfExperience,
          education: candidateData.education,
          noticePeriod,
          resume: file.filename,
          resumeText: '', // reset and parse asynchronously via event
          skills: {
            set: [], // clear existing skills associations
            connectOrCreate: skillsArray.map((name) => ({
              where: { name },
              create: { name },
            })),
          },
          jobId: (candidateData as any).jobId ? Number((candidateData as any).jobId) : undefined,
        },
        include: {
          skills: true,
          job: true,
        },
      });

      console.log('Updated Candidate: ', updatedCandidate);

      // Emit candidate.created event for asynchronous text extraction
      this.eventEmitter.emit('candidate.created', new CandidateCreatedEvent(updatedCandidate.id));

      return updatedCandidate;
    }

    // Create a new candidate record in the database
    const createdCandidate = await this.prisma.candidate.create({
      data: {
        firstName: candidateData.firstName,
        lastName: candidateData.lastName,
        mobile: candidateData.mobile,
        email: candidateData.email,
        yearsOfExperience,
        education: candidateData.education,
        noticePeriod,
        resume: file.filename,
        resumeText: '', // initially empty, parsed in event handler
        skills: {
          connectOrCreate: skillsArray.map((name) => ({
            where: { name },
            create: { name },
          })),
        },
        jobId: (candidateData as any).jobId ? Number((candidateData as any).jobId) : undefined,
      },
      include: {
        skills: true,
        job: true,
      },
    });

    console.log('Created Candidate: ', createdCandidate);

    // Emit candidate.created event for asynchronous text extraction
    this.eventEmitter.emit('candidate.created', new CandidateCreatedEvent(createdCandidate.id));

    return createdCandidate;
  }

  // get all candidate
  async findAll() {
    return await this.prisma.candidate.findMany({
      include: {
        skills: true,
        job: true,
      },
    });
  }

  // Get candidate by ID
  async findOne(id: number) {
    return await this.prisma.candidate.findUnique({
      where: { id },
      include: {
        skills: true,
        job: true,
      },
    });
  }

  // delete candidate by id
  async remove(id: number) {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    return await this.prisma.candidate.delete({
      where: { id },
    });
  }

  private cleanContactDetails(text: string): string {
    if (!text) return '';

    // Regex for emails
    const emailRegex = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g;

    // Regex for phone numbers (matches standard pattern with country code, area codes, spaces, dashes, parentheses)
    const phoneRegex = /(\(?\+?\d{1,4}\)?[-.\s]*)?\(?\d{2,5}\)?[-.\s()]*\d{3,4}[-.\s()]*\d{2,4}/g;

    let cleaned = text.replace(emailRegex, '');
    cleaned = cleaned.replace(phoneRegex, '');

    return cleaned;
  }

  async generateCleanedDoc(id: number): Promise<any> {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    if (!candidate.resumeText) {
      throw new NotFoundException(`Candidate with ID ${id} does not have any resume text to clean`);
    }

    let plainText = candidate.resumeText;
    const isHtml = /<[a-z][\s\S]*>/i.test(plainText);
    if (isHtml) {
      plainText = plainText
        .replace(/<\/p>/g, '\n')
        .replace(/<br\s*\/?>/g, '\n')
        .replace(/<[^>]*>/g, '');
    }

    const cleanedText = this.cleanContactDetails(plainText);

    // Generate docx
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: cleanedText.split('\n').map((line) => {
            return new Paragraph({
              children: [
                new TextRun({
                  text: line,
                  size: 24, // 24 half-points = 12pt font size
                }),
              ],
            });
          }),
        },
      ],
    });

    const docxBuffer = await Packer.toBuffer(doc);

    const fileName = `cleaned-resume-${id}-${Date.now()}.docx`;
    const filePath = join(process.cwd(), 'uploads', fileName);

    fs.writeFileSync(filePath, docxBuffer);

    // Save the doc link/filename in DB
    const updatedCandidate = await this.prisma.candidate.update({
      where: { id },
      data: {
        cleanedResume: fileName,
      },
      include: {
        skills: true,
      },
    });

    return updatedCandidate;
  }

  async findByEmail(email: string) {
    if (!email) return [];
    return await this.prisma.candidate.findMany({
      where: { email },
      include: {
        skills: true,
        job: true,
      },
      orderBy: {
        createdAt: 'desc',
      },
    });
  }

  async updateStatus(id: number, status: string) {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });
    if (!candidate) {
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }
    return await this.prisma.candidate.update({
      where: { id },
      data: { status },
      include: {
        skills: true,
        job: true,
      },
    });
  }

  async uploadCleanedResume(id: number, file: Express.Multer.File, resumeText?: string): Promise<any> {
    if (!file) {
      throw new NotFoundException('No file uploaded');
    }

    const allowedExtensions = ['.pdf', '.doc', '.docx'];
    const fileExtension = extname(file.originalname).toLowerCase();

    if (!allowedExtensions.includes(fileExtension)) {
      const tempPath = join(process.cwd(), 'uploads', file.filename);
      if (fs.existsSync(tempPath)) {
        fs.unlinkSync(tempPath);
      }
      throw new Error('Invalid file type. Only PDF and Word documents are allowed.');
    }

    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      const tempPath = join(process.cwd(), 'uploads', file.filename);
      if (fs.existsSync(tempPath)) {
        fs.unlinkSync(tempPath);
      }
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    // Delete old cleaned resume file if it exists
    if (candidate.cleanedResume) {
      const oldFilePath = join(process.cwd(), 'uploads', candidate.cleanedResume);
      try {
        if (fs.existsSync(oldFilePath)) {
          fs.unlinkSync(oldFilePath);
        }
      } catch (err) {
        console.error(`Error deleting old cleaned resume file: ${candidate.cleanedResume}`, err);
      }
    }

    // Update candidate record
    return await this.prisma.candidate.update({
      where: { id },
      data: {
        cleanedResume: file.filename,
        resumeText: resumeText || undefined,
      },
      include: {
        skills: true,
        job: true,
      },
    });
  }
}
