// src/candidate/candidate.service.ts
import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma.service';
import { CandidateDto } from 'src/Validations/candidate/create-candidate.dto';
import { join } from 'path';
import { extname } from 'path';
import { NotFoundException } from '@nestjs/common';
import * as fs from 'fs';
import * as mammoth from 'mammoth';
import { Document, Packer, Paragraph, TextRun } from 'docx';
import * as libre from 'libreoffice-convert';
import { promisify } from 'util';
import { execSync } from 'child_process';

import { EventEmitter2 } from '@nestjs/event-emitter';
import { CandidateCreatedEvent } from 'src/envent/events';

@Injectable()
export class CandidateService {
  constructor(
    private prisma: PrismaService,
    private eventEmitter: EventEmitter2,
  ) {}

  async uploadFileMulter(
    file: Express.Multer.File,
    candidateData: CandidateDto,
  ): Promise<any> {
    console.log('File ', file);

    const allowedExtensions = ['.pdf', '.doc', '.docx'];
    const fileExtension = extname(file.originalname);

    if (!allowedExtensions.includes(fileExtension)) {
      throw new Error(
        'Invalid file type. Only PDF and Word documents are allowed.',
      );
    }

    // Use the filename generated by Multer's diskStorage configuration
    const uniqueFileName = file.filename;

    const yearsOfExperience = Number(candidateData.yearsOfExperience);
    const noticePeriod = Number(candidateData.noticePeriod);

    let skillsArray: string[] = [];

    if (candidateData.skills) {
      if (typeof candidateData.skills === 'string') {
        skillsArray = candidateData.skills.split(',').map((s) => s.trim());
      } else if (Array.isArray(candidateData.skills)) {
        skillsArray = candidateData.skills.map((s) => s.trim());
      }
    }

    // Check if candidate with this email already exists to avoid unique constraint violations
    const existingCandidate = await this.prisma.candidate.findUnique({
      where: { email: candidateData.email },
    });

    if (existingCandidate) {
      // Delete old resume file if it exists and is different from the newly uploaded one
      if (existingCandidate.resume && existingCandidate.resume !== file.filename) {
        const oldFilePath = join(process.cwd(), 'uploads', existingCandidate.resume);
        try {
          if (fs.existsSync(oldFilePath)) {
            fs.unlinkSync(oldFilePath);
          }
        } catch (err) {
          console.error(`Error deleting old resume file: ${existingCandidate.resume}`, err);
        }
      }

      // Update candidate record
      const updatedCandidate = await this.prisma.candidate.update({
        where: { id: existingCandidate.id },
        data: {
          firstName: candidateData.firstName,
          lastName: candidateData.lastName,
          mobile: candidateData.mobile,
          yearsOfExperience,
          education: candidateData.education,
          noticePeriod,
          resume: file.filename,
          resumeText: '', // reset and parse asynchronously via event
          skills: {
            set: [], // clear existing skills associations
            connectOrCreate: skillsArray.map((name) => ({
              where: { name },
              create: { name },
            })),
          },
          jobId: (candidateData as any).jobId ? Number((candidateData as any).jobId) : undefined,
        },
        include: {
          skills: true,
          job: true,
        },
      });

      console.log('Updated Candidate: ', updatedCandidate);

      // Emit candidate.created event for asynchronous text extraction
      this.eventEmitter.emit('candidate.created', new CandidateCreatedEvent(updatedCandidate.id));

      return updatedCandidate;
    }

    // Create a new candidate record in the database
    const createdCandidate = await this.prisma.candidate.create({
      data: {
        firstName: candidateData.firstName,
        lastName: candidateData.lastName,
        mobile: candidateData.mobile,
        email: candidateData.email,
        yearsOfExperience,
        education: candidateData.education,
        noticePeriod,
        resume: file.filename,
        resumeText: '', // initially empty, parsed in event handler
        skills: {
          connectOrCreate: skillsArray.map((name) => ({
            where: { name },
            create: { name },
          })),
        },
        jobId: (candidateData as any).jobId ? Number((candidateData as any).jobId) : undefined,
      },
      include: {
        skills: true,
        job: true,
      },
    });

    console.log('Created Candidate: ', createdCandidate);

    // Emit candidate.created event for asynchronous text extraction
    this.eventEmitter.emit('candidate.created', new CandidateCreatedEvent(createdCandidate.id));

    return createdCandidate;
  }

  // get all candidate
  async findAll() {
    return await this.prisma.candidate.findMany({
      include: {
        skills: true,
        job: true,
      },
    });
  }

  // Get candidate by ID
  async findOne(id: number) {
    return await this.prisma.candidate.findUnique({
      where: { id },
      include: {
        skills: true,
        job: true,
      },
    });
  }

  // delete candidate by id
  async remove(id: number) {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    return await this.prisma.candidate.delete({
      where: { id },
    });
  }

  private cleanContactDetails(text: string): string {
    if (!text) return '';

    // Regex for emails
    const emailRegex = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g;

    // Regex for phone numbers (matches standard pattern with country code, area codes, spaces, dashes, parentheses)
    const phoneRegex = /(\(?\+?\d{1,4}\)?[-.\s]*)?\(?\d{2,5}\)?[-.\s()]*\d{3,4}[-.\s()]*\d{2,4}/g;

    let cleaned = text.replace(emailRegex, '');
    cleaned = cleaned.replace(phoneRegex, '');

    return cleaned;
  }

  async generateCleanedDoc(id: number): Promise<any> {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    if (!candidate.resumeText) {
      throw new NotFoundException(`Candidate with ID ${id} does not have any resume text to clean`);
    }

    let plainText = candidate.resumeText;
    const isHtml = /<[a-z][\s\S]*>/i.test(plainText);
    if (isHtml) {
      plainText = plainText
        .replace(/<\/p>/g, '\n')
        .replace(/<br\s*\/?>/g, '\n')
        .replace(/<[^>]*>/g, '');
    }

    const cleanedText = this.cleanContactDetails(plainText);

    // Generate docx
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: cleanedText.split('\n').map((line) => {
            return new Paragraph({
              children: [
                new TextRun({
                  text: line,
                  size: 24, // 24 half-points = 12pt font size
                }),
              ],
            });
          }),
        },
      ],
    });

    const docxBuffer = await Packer.toBuffer(doc);

    const fileName = `cleaned-resume-${id}-${Date.now()}.docx`;
    const filePath = join(process.cwd(), 'uploads', fileName);

    fs.writeFileSync(filePath, docxBuffer);

    // Save the doc link/filename in DB
    const updatedCandidate = await this.prisma.candidate.update({
      where: { id },
      data: {
        cleanedResume: fileName,
      },
      include: {
        skills: true,
      },
    });

    return updatedCandidate;
  }

  async findByEmail(email: string) {
    if (!email) return [];
    return await this.prisma.candidate.findMany({
      where: { email },
      include: {
        skills: true,
        job: true,
      },
      orderBy: {
        createdAt: 'desc',
      },
    });
  }

  async updateStatus(id: number, status: string) {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });
    if (!candidate) {
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }
    return await this.prisma.candidate.update({
      where: { id },
      data: { status },
      include: {
        skills: true,
        job: true,
      },
    });
  }

  async uploadCleanedResume(id: number, file: Express.Multer.File, resumeText?: string): Promise<any> {
    if (!file) {
      throw new NotFoundException('No file uploaded');
    }

    const allowedExtensions = ['.pdf', '.doc', '.docx'];
    const fileExtension = extname(file.originalname).toLowerCase();

    if (!allowedExtensions.includes(fileExtension)) {
      const tempPath = join(process.cwd(), 'uploads', file.filename);
      if (fs.existsSync(tempPath)) {
        fs.unlinkSync(tempPath);
      }
      throw new Error('Invalid file type. Only PDF and Word documents are allowed.');
    }

    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      const tempPath = join(process.cwd(), 'uploads', file.filename);
      if (fs.existsSync(tempPath)) {
        fs.unlinkSync(tempPath);
      }
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    // Delete old cleaned resume file if it exists
    if (candidate.cleanedResume) {
      const oldFilePath = join(process.cwd(), 'uploads', candidate.cleanedResume);
      try {
        if (fs.existsSync(oldFilePath)) {
          fs.unlinkSync(oldFilePath);
        }
      } catch (err) {
        console.error(`Error deleting old cleaned resume file: ${candidate.cleanedResume}`, err);
      }
    }

    // Extract text from the new file
    let extractedText = '';
    const filePath = join(process.cwd(), 'uploads', file.filename);
    try {
      if (fs.existsSync(filePath)) {
        const buffer = fs.readFileSync(filePath);
        if (fileExtension === '.pdf') {
          const outputDir = join(process.cwd(), 'uploads');
          const htmlFileName = file.filename.replace(/\.pdf$/i, '.html');
          const htmlFilePath = join(outputDir, htmlFileName);

          try {
            // Convert to HTML using pdftohtml to preserve exact styles, positions, and fonts
            const command = `pdftohtml -s -noframes -c -dataurls "${filePath}" "${htmlFilePath}"`;
            execSync(command);

            if (fs.existsSync(htmlFilePath)) {
              const rawHtml = fs.readFileSync(htmlFilePath, 'utf8');
              extractedText = cleanPdftohtmlOutline(rawHtml);
              fs.unlinkSync(htmlFilePath);
              console.log(`[Cleaned Upload] pdftohtml conversion succeeded for candidate ID: ${id}`);
            }
          } catch (execError) {
            console.error('[Cleaned Upload] pdftohtml conversion failed:', execError.message);
          }
        } else if (fileExtension === '.docx' || fileExtension === '.doc') {
          const outputDir = join(process.cwd(), 'uploads');
          const htmlFileName = file.filename.replace(/\.(docx|doc)$/i, '.html');
          const htmlFilePath = join(outputDir, htmlFileName);

          try {
            // Convert to HTML using headless LibreOffice to preserve exact layout and styles of Word files
            const command = `libreoffice --headless --convert-to html --outdir "${outputDir}" "${filePath}"`;
            execSync(command);

            if (fs.existsSync(htmlFilePath)) {
              extractedText = fs.readFileSync(htmlFilePath, 'utf8');
              fs.unlinkSync(htmlFilePath);
              console.log(`[Cleaned Upload] LibreOffice Word-to-HTML conversion succeeded for candidate ID: ${id}`);
            }
          } catch (libreOfficeError) {
            console.warn('[Cleaned Upload] LibreOffice conversion failed, falling back to Mammoth:', libreOfficeError.message);
            try {
              const result = await mammoth.convertToHtml({ buffer });
              extractedText = result.value || '';
            } catch (mammothError) {
              console.error('[Cleaned Upload] Fallback Mammoth DOCX conversion failed:', mammothError);
            }
          }
        }
      }
    } catch (error) {
      console.error('Error extracting text from uploaded cleaned resume:', error);
    }

    // Update candidate record
    return await this.prisma.candidate.update({
      where: { id },
      data: {
        cleanedResume: file.filename,
        resumeText: extractedText || resumeText || undefined,
      },
      include: {
        skills: true,
        job: true,
      },
    });
  }

  async updateResumeFile(id: number, file?: Express.Multer.File, resumeText?: string): Promise<any> {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      if (file) {
        const tempPath = join(process.cwd(), 'uploads', file.filename);
        if (fs.existsSync(tempPath)) {
          fs.unlinkSync(tempPath);
        }
      }
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    if (!file && !resumeText) {
      throw new Error('Either file or resumeText must be provided.');
    }

    let resumeFilename = candidate.resume;
    let extractedText = resumeText || '';

    if (file) {
      const allowedExtensions = ['.pdf', '.doc', '.docx'];
      const fileExtension = extname(file.originalname).toLowerCase();

      if (!allowedExtensions.includes(fileExtension)) {
        const tempPath = join(process.cwd(), 'uploads', file.filename);
        if (fs.existsSync(tempPath)) {
          fs.unlinkSync(tempPath);
        }
        throw new Error('Invalid file type. Only PDF and Word documents are allowed.');
      }

      // Delete old resume file if it exists
      if (candidate.resume) {
        const oldFilePath = join(process.cwd(), 'uploads', candidate.resume);
        try {
          if (fs.existsSync(oldFilePath)) {
            fs.unlinkSync(oldFilePath);
          }
        } catch (err) {
          console.error(`Error deleting old resume file: ${candidate.resume}`, err);
        }
      }

      resumeFilename = file.filename;

      // Extract text synchronously if not provided
      if (!resumeText) {
        const filePath = join(process.cwd(), 'uploads', file.filename);
        try {
          if (fs.existsSync(filePath)) {
            const buffer = fs.readFileSync(filePath);
            if (fileExtension === '.pdf') {
              const outputDir = join(process.cwd(), 'uploads');
              const htmlFileName = file.filename.replace(/\.pdf$/i, '.html');
              const htmlFilePath = join(outputDir, htmlFileName);

              try {
                const command = `pdftohtml -s -noframes -c -dataurls "${filePath}" "${htmlFilePath}"`;
                execSync(command);

                if (fs.existsSync(htmlFilePath)) {
                  const rawHtml = fs.readFileSync(htmlFilePath, 'utf8');
                  extractedText = cleanPdftohtmlOutline(rawHtml);
                  fs.unlinkSync(htmlFilePath);
                  console.log(`[Sync Extract] pdftohtml conversion succeeded for candidate ID: ${id}`);
                }
              } catch (execError) {
                console.error('[Sync Extract] pdftohtml conversion failed:', execError.message);
              }
            } else if (fileExtension === '.docx' || fileExtension === '.doc') {
              const outputDir = join(process.cwd(), 'uploads');
              const htmlFileName = file.filename.replace(/\.(docx|doc)$/i, '.html');
              const htmlFilePath = join(outputDir, htmlFileName);

              try {
                const command = `libreoffice --headless --convert-to html --outdir "${outputDir}" "${filePath}"`;
                execSync(command);

                if (fs.existsSync(htmlFilePath)) {
                  extractedText = fs.readFileSync(htmlFilePath, 'utf8');
                  fs.unlinkSync(htmlFilePath);
                  console.log(`[Sync Extract] LibreOffice Word-to-HTML conversion succeeded for candidate ID: ${id}`);
                }
              } catch (libreOfficeError) {
                console.warn('[Sync Extract] LibreOffice conversion failed, falling back to Mammoth:', libreOfficeError.message);
                try {
                  const result = await mammoth.convertToHtml({ buffer });
                  extractedText = result.value || '';
                } catch (mammothError) {
                  console.error('[Sync Extract] Fallback Mammoth DOCX conversion failed:', mammothError);
                }
              }
            }
          }
        } catch (err) {
          console.error('Error extracting text during resume update:', err);
        }
      }
    } else if (resumeText) {
      // Generate premium PDF directly from edited HTML using LibreOffice
      const tempHtmlName = `temp-${id}-${Date.now()}.html`;
      const tempHtmlPath = join(process.cwd(), 'uploads', tempHtmlName);

      // Add clean styles to ensure beautiful styling when converting html to pdf
      const styledHtml = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <style>
            @page {
              size: A4;
              margin: 1.2in 1in 1.2in 1in;
            }
            body {
              font-family: Arial, Helvetica, sans-serif;
              line-height: 1.35;
              color: #2b2b2b;
              font-size: 11pt;
            }
            p { margin-top: 0; margin-bottom: 6px; }
            h1, h2, h3, h4, h5, h6 { 
              margin-top: 14px; 
              margin-bottom: 6px; 
              color: #111111;
              font-weight: bold;
            }
            h1 { font-size: 20pt; text-align: center; margin-bottom: 12px; }
            h2 { font-size: 14pt; border-bottom: 1.5px solid #4a5568; padding-bottom: 3px; margin-top: 18px; }
            h3 { font-size: 12pt; }
            table { 
              width: 100%; 
              border-collapse: collapse; 
              margin-top: 4px; 
              margin-bottom: 8px; 
              page-break-inside: avoid;
            }
            td { 
              padding: 2px 4px; 
              vertical-align: top; 
            }
            ul, ol { margin-top: 4px; margin-bottom: 6px; padding-left: 20px; }
            li { margin-bottom: 3px; }
          </style>
        </head>
        <body>
          ${resumeText}
        </body>
        </html>
      `;

      fs.writeFileSync(tempHtmlPath, styledHtml);

      try {
        const outputDir = join(process.cwd(), 'uploads');
        const pdfFileName = `resume-${id}-${Date.now()}.pdf`;
        const tempPdfPath = join(outputDir, tempHtmlName.replace(/\.html$/i, '.pdf'));

        const command = `libreoffice --headless --convert-to pdf --outdir "${outputDir}" "${tempHtmlPath}"`;
        execSync(command);

        if (fs.existsSync(tempHtmlPath)) {
          fs.unlinkSync(tempHtmlPath);
        }

        if (fs.existsSync(tempPdfPath)) {
          const finalPdfPath = join(outputDir, pdfFileName);
          fs.renameSync(tempPdfPath, finalPdfPath);
          resumeFilename = pdfFileName;

          // Delete old resume file if it exists
          if (candidate.resume) {
            const oldFilePath = join(process.cwd(), 'uploads', candidate.resume);
            try {
              if (fs.existsSync(oldFilePath)) {
                fs.unlinkSync(oldFilePath);
              }
            } catch (err) {
              console.error(`Error deleting old resume file: ${candidate.resume}`, err);
            }
          }
          console.log(`[Backend PDF Gen] PDF generated successfully for candidate ID: ${id}`);
        }
      } catch (err) {
        console.error('Error generating PDF from resumeText on server:', err);
        if (fs.existsSync(tempHtmlPath)) {
          fs.unlinkSync(tempHtmlPath);
        }
      }
    }

    // Update candidate's resume filename and text in the database
    const updatedCandidate = await this.prisma.candidate.update({
      where: { id },
      data: {
        resume: resumeFilename,
        resumeText: extractedText,
      },
      include: {
        skills: true,
        job: true,
      },
    });

    return updatedCandidate;
  }
}

function cleanPdftohtmlOutline(html: string): string {
  if (!html) return html;
  // Strip <hr/> and the Document Outline section
  let cleaned = html.replace(/<hr\s*\/?>\s*<a\s+name="outline">[\s\S]*?(<\/body>|<\/html>|$)/i, "$1");
  cleaned = cleaned.replace(/<a\s+name="outline">[\s\S]*?(<\/body>|<\/html>|$)/i, "$1");
  cleaned = cleaned.replace(/<h1>Document Outline<\/h1>[\s\S]*?(<\/body>|<\/html>|$)/i, "$1");
  return cleaned;
}

