// src/candidate/candidate.service.ts
import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma.service';
import { CandidateDto } from 'src/Validations/candidate/create-candidate.dto';
import { join } from 'path';
import { extname } from 'path';
import { NotFoundException } from '@nestjs/common';
import * as fs from 'fs';
import * as mammoth from 'mammoth';
import { Document, Packer, Paragraph, TextRun } from 'docx';
import * as libre from 'libreoffice-convert';
import { promisify } from 'util';
import { execSync } from 'child_process';

import { EventEmitter2 } from '@nestjs/event-emitter';
import { CandidateCreatedEvent } from 'src/envent/events';

@Injectable()
export class CandidateService {
  constructor(
    private prisma: PrismaService,
    private eventEmitter: EventEmitter2,
  ) {}

  async uploadFileMulter(
    file: Express.Multer.File,
    candidateData: CandidateDto,
  ): Promise<any> {
    console.log('File ', file);

    const allowedExtensions = ['.pdf', '.doc', '.docx'];
    const fileExtension = extname(file.originalname);

    if (!allowedExtensions.includes(fileExtension)) {
      throw new Error(
        'Invalid file type. Only PDF and Word documents are allowed.',
      );
    }

    // Use the filename generated by Multer's diskStorage configuration
    const uniqueFileName = file.filename;

    const yearsOfExperience = Number(candidateData.yearsOfExperience);
    const noticePeriod = Number(candidateData.noticePeriod);

    let skillsArray: string[] = [];

    if (candidateData.skills) {
      if (typeof candidateData.skills === 'string') {
        skillsArray = candidateData.skills.split(',').map((s) => s.trim());
      } else if (Array.isArray(candidateData.skills)) {
        skillsArray = candidateData.skills.map((s) => s.trim());
      }
    }

    // Check if candidate with this email already exists to avoid unique constraint violations
    const existingCandidate = await this.prisma.candidate.findUnique({
      where: { email: candidateData.email },
    });

    if (existingCandidate) {
      // Delete old resume file if it exists and is different from the newly uploaded one
      if (existingCandidate.resume && existingCandidate.resume !== file.filename) {
        const oldFilePath = join(process.cwd(), 'uploads', existingCandidate.resume);
        try {
          if (fs.existsSync(oldFilePath)) {
            fs.unlinkSync(oldFilePath);
          }
        } catch (err) {
          console.error(`Error deleting old resume file: ${existingCandidate.resume}`, err);
        }
      }

      // Update candidate record
      const updatedCandidate = await this.prisma.candidate.update({
        where: { id: existingCandidate.id },
        data: {
          firstName: candidateData.firstName,
          lastName: candidateData.lastName,
          mobile: candidateData.mobile,
          yearsOfExperience,
          education: candidateData.education,
          noticePeriod,
          resume: file.filename,
          resumeText: '', // reset and parse asynchronously via event
          skills: {
            set: [], // clear existing skills associations
            connectOrCreate: skillsArray.map((name) => ({
              where: { name },
              create: { name },
            })),
          },
          jobId: (candidateData as any).jobId ? Number((candidateData as any).jobId) : undefined,
        },
        include: {
          skills: true,
          job: true,
        },
      });

      console.log('Updated Candidate: ', updatedCandidate);

      // Emit candidate.created event for asynchronous text extraction
      this.eventEmitter.emit('candidate.created', new CandidateCreatedEvent(updatedCandidate.id));

      return updatedCandidate;
    }

    // Create a new candidate record in the database
    const createdCandidate = await this.prisma.candidate.create({
      data: {
        firstName: candidateData.firstName,
        lastName: candidateData.lastName,
        mobile: candidateData.mobile,
        email: candidateData.email,
        yearsOfExperience,
        education: candidateData.education,
        noticePeriod,
        resume: file.filename,
        resumeText: '', // initially empty, parsed in event handler
        skills: {
          connectOrCreate: skillsArray.map((name) => ({
            where: { name },
            create: { name },
          })),
        },
        jobId: (candidateData as any).jobId ? Number((candidateData as any).jobId) : undefined,
      },
      include: {
        skills: true,
        job: true,
      },
    });

    console.log('Created Candidate: ', createdCandidate);

    // Emit candidate.created event for asynchronous text extraction
    this.eventEmitter.emit('candidate.created', new CandidateCreatedEvent(createdCandidate.id));

    return createdCandidate;
  }

  // get all candidate
  async findAll(
    page?: number,
    limit?: number,
    search?: string,
    skill?: string,
    experience?: string,
    userId?: number,
    role?: string,
  ) {
    const where: any = {};

    // 1. Company User filter
    if (role && role !== 'ADMIN' && userId) {
      where.job = {
        createdById: userId,
      };
    }

    // 2. Skill Filter
    if (skill) {
      where.skills = {
        some: {
          name: {
            equals: skill,
            mode: 'insensitive',
          },
        },
      };
    }

    // 3. Experience Filter
    if (experience) {
      if (experience === '0-2') {
        where.yearsOfExperience = { gte: 0, lte: 2 };
      } else if (experience === '3-5') {
        where.yearsOfExperience = { gte: 3, lte: 5 };
      } else if (experience === '6-9') {
        where.yearsOfExperience = { gte: 6, lte: 9 };
      } else if (experience === '10+') {
        where.yearsOfExperience = { gte: 10 };
      }
    }

    // 4. Search Term Filter
    if (search && search.trim()) {
      const term = search.trim();
      where.OR = [
        { firstName: { contains: term, mode: 'insensitive' } },
        { lastName: { contains: term, mode: 'insensitive' } },
        { email: { contains: term, mode: 'insensitive' } },
        { mobile: { contains: term, mode: 'insensitive' } },
        { education: { contains: term, mode: 'insensitive' } },
        { resumeText: { contains: term, mode: 'insensitive' } },
        {
          skills: {
            some: {
              name: { contains: term, mode: 'insensitive' },
            },
          },
        },
      ];
    }

    const skip = page && limit ? (page - 1) * limit : undefined;
    const take = limit ? limit : undefined;

    const [candidates, total] = await Promise.all([
      this.prisma.candidate.findMany({
        where,
        skip,
        take,
        include: {
          skills: true,
          job: true,
        },
        orderBy: {
          id: 'desc',
        },
      }),
      this.prisma.candidate.count({ where }),
    ]);

    return {
      data: candidates,
      total,
      page: page || 1,
      limit: limit || total,
      totalPages: limit ? Math.ceil(total / limit) : 1,
    };
  }

  // Get candidate by ID
  async findOne(id: number) {
    return await this.prisma.candidate.findUnique({
      where: { id },
      include: {
        skills: true,
        job: true,
      },
    });
  }

  // delete candidate by id
  async remove(id: number) {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    return await this.prisma.candidate.delete({
      where: { id },
    });
  }

  private cleanContactDetails(text: string): string {
    if (!text) return '';

    // Regex for emails
    const emailRegex = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g;

    // Regex for phone numbers (matches standard pattern with country code, area codes, spaces, dashes, parentheses)
    const phoneRegex = /(\(?\+?\d{1,4}\)?[-.\s]*)?\(?\d{2,5}\)?[-.\s()]*\d{3,4}[-.\s()]*\d{2,4}/g;

    let cleaned = text.replace(emailRegex, '');
    cleaned = cleaned.replace(phoneRegex, '');

    return cleaned;
  }

  async generateCleanedDoc(id: number): Promise<any> {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    if (!candidate.resumeText) {
      throw new NotFoundException(`Candidate with ID ${id} does not have any resume text to clean`);
    }

    let plainText = candidate.resumeText;
    const isHtml = /<[a-z][\s\S]*>/i.test(plainText);
    if (isHtml) {
      plainText = plainText
        .replace(/<\/p>/g, '\n')
        .replace(/<br\s*\/?>/g, '\n')
        .replace(/<[^>]*>/g, '');
    }

    const cleanedText = this.cleanContactDetails(plainText);

    // Generate docx
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: cleanedText.split('\n').map((line) => {
            return new Paragraph({
              children: [
                new TextRun({
                  text: line,
                  size: 24, // 24 half-points = 12pt font size
                }),
              ],
            });
          }),
        },
      ],
    });

    const docxBuffer = await Packer.toBuffer(doc);

    const fileName = `cleaned-resume-${id}-${Date.now()}.docx`;
    const filePath = join(process.cwd(), 'uploads', fileName);

    fs.writeFileSync(filePath, docxBuffer);

    // Save the doc link/filename in DB
    const updatedCandidate = await this.prisma.candidate.update({
      where: { id },
      data: {
        cleanedResume: fileName,
      },
      include: {
        skills: true,
      },
    });

    return updatedCandidate;
  }

  async findByEmail(email: string) {
    if (!email) return [];
    return await this.prisma.candidate.findMany({
      where: { email },
      include: {
        skills: true,
        job: true,
      },
      orderBy: {
        createdAt: 'desc',
      },
    });
  }

  async updateStatus(id: number, status: string) {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });
    if (!candidate) {
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }
    return await this.prisma.candidate.update({
      where: { id },
      data: { status },
      include: {
        skills: true,
        job: true,
      },
    });
  }

  async uploadCleanedResume(id: number, file: Express.Multer.File, resumeText?: string): Promise<any> {
    if (!file) {
      throw new NotFoundException('No file uploaded');
    }

    const allowedExtensions = ['.pdf', '.doc', '.docx'];
    const fileExtension = extname(file.originalname).toLowerCase();

    if (!allowedExtensions.includes(fileExtension)) {
      const tempPath = join(process.cwd(), 'uploads', file.filename);
      if (fs.existsSync(tempPath)) {
        fs.unlinkSync(tempPath);
      }
      throw new Error('Invalid file type. Only PDF and Word documents are allowed.');
    }

    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      const tempPath = join(process.cwd(), 'uploads', file.filename);
      if (fs.existsSync(tempPath)) {
        fs.unlinkSync(tempPath);
      }
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    // Delete old cleaned resume file if it exists
    if (candidate.cleanedResume) {
      const oldFilePath = join(process.cwd(), 'uploads', candidate.cleanedResume);
      try {
        if (fs.existsSync(oldFilePath)) {
          fs.unlinkSync(oldFilePath);
        }
      } catch (err) {
        console.error(`Error deleting old cleaned resume file: ${candidate.cleanedResume}`, err);
      }
    }

    // Extract text from the new file
    let extractedText = '';
    const filePath = join(process.cwd(), 'uploads', file.filename);
    try {
      if (fs.existsSync(filePath)) {
        const buffer = fs.readFileSync(filePath);
        if (fileExtension === '.pdf') {
          const outputDir = join(process.cwd(), 'uploads');
          const htmlFileName = file.filename.replace(/\.pdf$/i, '.html');
          const htmlFilePath = join(outputDir, htmlFileName);

          try {
            // Convert to HTML using pdftohtml to preserve exact styles, positions, and fonts
            const command = `pdftohtml -s -noframes -c -dataurls "${filePath}" "${htmlFilePath}"`;
            execSync(command);

            if (fs.existsSync(htmlFilePath)) {
              const rawHtml = fs.readFileSync(htmlFilePath, 'utf8');
              extractedText = cleanPdftohtmlOutline(rawHtml);
              fs.unlinkSync(htmlFilePath);
              console.log(`[Cleaned Upload] pdftohtml conversion succeeded for candidate ID: ${id}`);
            }
          } catch (execError) {
            console.error('[Cleaned Upload] pdftohtml conversion failed:', execError.message);
          }
        } else if (fileExtension === '.docx' || fileExtension === '.doc') {
          const outputDir = join(process.cwd(), 'uploads');
          const htmlFileName = file.filename.replace(/\.(docx|doc)$/i, '.html');
          const htmlFilePath = join(outputDir, htmlFileName);

          try {
            // Convert to HTML using headless LibreOffice to preserve exact layout and styles of Word files
            const command = `libreoffice --headless --convert-to html --outdir "${outputDir}" "${filePath}"`;
            execSync(command);

            if (fs.existsSync(htmlFilePath)) {
              extractedText = fs.readFileSync(htmlFilePath, 'utf8');
              fs.unlinkSync(htmlFilePath);
              console.log(`[Cleaned Upload] LibreOffice Word-to-HTML conversion succeeded for candidate ID: ${id}`);
            }
          } catch (libreOfficeError) {
            console.warn('[Cleaned Upload] LibreOffice conversion failed, falling back to Mammoth:', libreOfficeError.message);
            try {
              const result = await mammoth.convertToHtml({ buffer });
              extractedText = result.value || '';
            } catch (mammothError) {
              console.error('[Cleaned Upload] Fallback Mammoth DOCX conversion failed:', mammothError);
            }
          }
        }
      }
    } catch (error) {
      console.error('Error extracting text from uploaded cleaned resume:', error);
    }

    // Update candidate record
    return await this.prisma.candidate.update({
      where: { id },
      data: {
        cleanedResume: file.filename,
        resumeText: extractedText || resumeText || undefined,
      },
      include: {
        skills: true,
        job: true,
      },
    });
  }

  /**
   * Generates a high-quality PDF buffer from HTML content using Puppeteer headless browser.
   */
  async generatePdfFromHtml(htmlContent: string): Promise<Buffer> {
    const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });
    try {
      const page = await browser.newPage();
      
      const printFriendlyHtml = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <style>
            @page {
              size: A4;
              margin: 15mm;
            }
            body {
              font-family: Arial, Helvetica, sans-serif;
              line-height: 1.4;
              color: #2c3e50;
              background-color: #ffffff;
            }
            p { margin: 0 0 8px 0; }
            h1, h2, h3, h4, h5, h6 { 
              color: #2c3e50; 
              margin-top: 15px; 
              margin-bottom: 8px;
              font-weight: bold;
            }
            h1 { font-size: 24px; text-align: center; border-bottom: 2px solid #2c3e50; padding-bottom: 5px; }
            h2 { font-size: 18px; border-bottom: 1.5px solid #bdc3c7; padding-bottom: 3px; }
            table { width: 100%; border-collapse: collapse; margin: 10px 0; }
            td { padding: 4px; vertical-align: top; }
            ul, ol { margin: 5px 0; padding-left: 20px; }
            li { margin-bottom: 4px; }
          </style>
        </head>
        <body>
          ${htmlContent}
        </body>
        </html>
      `;

      await page.setContent(printFriendlyHtml, { waitUntil: 'networkidle0' });
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
      });
      return Buffer.from(pdfBuffer);
    } finally {
      await browser.close();
    }
  }

  /**
   * Generates a DOCX document buffer from HTML content.
   */
  async generateDocxFromHtml(htmlContent: string): Promise<Buffer> {
    const puppeteer = require('puppeteer');
    const htmlToDocx = require('html-to-docx');
    
    let cleanSemanticHtml = '';
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });

    try {
      const page = await browser.newPage();
      await page.setContent(htmlContent || '<div></div>', { waitUntil: 'networkidle0' });

      // Reconstruct document in visual reading order (top-to-bottom, left-to-right)
      cleanSemanticHtml = await page.evaluate(() => {
        // Find all text elements (p, div, span, etc.)
        const elements = Array.from(document.querySelectorAll('p, div, span, h1, h2, h3, h4, h5, h6, li'));
        
        // Filter out elements that don't have direct text, or are layout containers
        const textNodes = elements.filter(el => {
          const hasChildElement = Array.from(el.children).some(child => 
            ['P', 'DIV', 'SPAN', 'H1', 'H2', 'H3', 'LI'].includes(child.tagName)
          );
          const hasText = el.textContent && el.textContent.trim().length > 0;
          const isBase64 = el.innerHTML.includes('data:image');
          return hasText && !hasChildElement && !isBase64;
        });

        // Get bounding boxes of all text elements
        const positionedItems = textNodes.map(el => {
          const rect = el.getBoundingClientRect();
          return {
            text: el.textContent ? el.textContent.trim() : '',
            top: rect.top + window.scrollY,
            left: rect.left + window.scrollX,
            width: rect.width,
            fontSize: window.getComputedStyle(el).fontSize,
            fontWeight: window.getComputedStyle(el).fontWeight,
          };
        });

        // Split items into Left Column (Sidebar) and Right Column (Main)
        // Divider: 300px (to align sidebar boundary nicely)
        const leftItems = positionedItems.filter(item => item.left < 300);
        const rightItems = positionedItems.filter(item => item.left >= 300);

        // Group left column items into lines
        const leftLines: { top: number; items: typeof leftItems }[] = [];
        leftItems.forEach(item => {
          let foundLine = leftLines.find(line => Math.abs(line.top - item.top) < 6);
          if (foundLine) {
            foundLine.items.push(item);
          } else {
            leftLines.push({ top: item.top, items: [item] });
          }
        });
        leftLines.sort((a, b) => a.top - b.top);
        leftLines.forEach(line => line.items.sort((a, b) => a.left - b.left));

        // Group right column items into lines
        const rightLines: { top: number; items: typeof rightItems }[] = [];
        rightItems.forEach(item => {
          let foundLine = rightLines.find(line => Math.abs(line.top - item.top) < 6);
          if (foundLine) {
            foundLine.items.push(item);
          } else {
            rightLines.push({ top: item.top, items: [item] });
          }
        });
        rightLines.sort((a, b) => a.top - b.top);
        rightLines.forEach(line => line.items.sort((a, b) => a.left - b.left));

        // Helper function to merge text elements on the same line and resolve pdf kerning word-splitting bugs
        const mergeLineItems = (items: typeof positionedItems) => {
          if (items.length === 0) return '';
          let merged = items[0].text;
          for (let i = 1; i < items.length; i++) {
            const prev = items[i - 1];
            const curr = items[i];
            const gap = curr.left - (prev.left + prev.width);
            
            // If the visual horizontal gap is larger than 4px, join with space.
            // Otherwise, merge characters directly to heal split words.
            if (gap > 4) {
              merged += ' ' + curr.text;
            } else {
              merged += curr.text;
            }
          }
          return merged;
        };

        // Build Left Column HTML (White text, dark background)
        let leftHtml = '';
        leftLines.forEach(line => {
          const mergedText = mergeLineItems(line.items);
          if (!mergedText) return;

          const firstItem = line.items[0];
          const isBold = firstItem.fontWeight === 'bold' || parseInt(firstItem.fontWeight) >= 600;
          const fontSizePx = parseFloat(firstItem.fontSize);

          if (fontSizePx >= 18) {
            leftHtml += `<h1 style="font-size: 18pt; font-weight: bold; color: #ffffff; margin-bottom: 8pt; margin-top: 10pt; font-family: Arial;">${mergedText}</h1>\n`;
          } else if (isBold && (fontSizePx >= 13 || (mergedText.length < 30 && !mergedText.endsWith('.')))) {
            leftHtml += `<h2 style="font-size: 12pt; font-weight: bold; color: #ffffff; border-bottom: 1px solid #ffffff; margin-top: 16pt; margin-bottom: 8pt; padding-bottom: 2pt; font-family: Arial; text-transform: uppercase;">${mergedText}</h2>\n`;
          } else {
            leftHtml += `<p style="font-size: 9.5pt; color: #eeeeee; line-height: 1.35; margin-bottom: 6pt; font-family: Arial;">${mergedText}</p>\n`;
          }
        });

        // Build Right Column HTML (Dark text, white background)
        let rightHtml = '';
        rightLines.forEach(line => {
          const mergedText = mergeLineItems(line.items);
          if (!mergedText) return;

          const firstItem = line.items[0];
          const isBold = firstItem.fontWeight === 'bold' || parseInt(firstItem.fontWeight) >= 600;
          const fontSizePx = parseFloat(firstItem.fontSize);

          if (isBold && (fontSizePx >= 13 || (mergedText.length < 50 && !mergedText.endsWith('.')))) {
            rightHtml += `<h2 style="font-size: 13pt; font-weight: bold; color: #2b0f54; border-bottom: 1px solid #e2e8f0; margin-top: 16pt; margin-bottom: 8pt; padding-bottom: 2pt; font-family: Arial; text-transform: uppercase;">${mergedText}</h2>\n`;
          } else if (mergedText.startsWith('•') || mergedText.startsWith('-') || mergedText.startsWith('*')) {
            const cleanLi = mergedText.replace(/^[•\-\*]\s*/, '');
            rightHtml += `<ul style="margin-bottom: 4pt; padding-left: 20pt; font-family: Arial;"><li style="font-size: 11pt; line-height: 1.35; color: #333333;">${cleanLi}</li></ul>\n`;
          } else {
            rightHtml += `<p style="font-size: 11pt; line-height: 1.35; margin-bottom: 6pt; color: #333333; font-family: Arial;">${mergedText}</p>\n`;
          }
        });

        // Assemble columns inside a full-height Word table (Wider sidebar layout: 35% / 65%)
        return `
          <table style="width: 100%; border: none; border-collapse: collapse;">
            <tr>
              <td width="35%" style="background-color: #2b0f54; color: #ffffff; padding: 36pt 18pt; vertical-align: top;">
                ${leftHtml}
              </td>
              <td width="65%" style="background-color: #ffffff; color: #333333; padding: 36pt 24pt; vertical-align: top;">
                ${rightHtml}
              </td>
            </tr>
          </table>
        `;
      });
    } catch (err) {
      console.error('[Premium DOCX Gen] Puppeteer preprocessing failed, falling back to regex clean:', err);
      let fallback = htmlContent || '';
      fallback = fallback.replace(/<img[^>]+src="data:image\/[^>]+>/gi, '');
      fallback = fallback.replace(/<img[^>]+alt="background image"[^>]*>/gi, '');
      fallback = fallback.replace(/position:\s*(absolute|relative);?/gi, '');
      fallback = fallback.replace(/top:\s*\d+(px|pt|em|%)?;?/gi, '');
      fallback = fallback.replace(/left:\s*\d+(px|pt|em|%)?;?/gi, '');
      fallback = fallback.replace(/white-space:\s*nowrap;?/gi, '');
      cleanSemanticHtml = fallback;
    } finally {
      await browser.close();
    }

    const styledHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
          }
        </style>
      </head>
      <body>
        ${cleanSemanticHtml}
      </body>
      </html>
    `;

    const docxBuffer = await htmlToDocx(styledHtml, null, {
      table: { row: { cantSplit: true } },
      footer: false,
      pageNumber: false,
      margins: {
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
      },
    });
    return Buffer.from(docxBuffer);
  }

  async updateResumeFile(id: number, file?: Express.Multer.File, resumeText?: string): Promise<any> {
    const candidate = await this.prisma.candidate.findUnique({
      where: { id },
    });

    if (!candidate) {
      if (file) {
        const tempPath = join(process.cwd(), 'uploads', file.filename);
        if (fs.existsSync(tempPath)) {
          fs.unlinkSync(tempPath);
        }
      }
      throw new NotFoundException(`Candidate with ID ${id} not found`);
    }

    if (!file && !resumeText) {
      throw new Error('Either file or resumeText must be provided.');
    }

    let resumeFilename = candidate.resume;
    let extractedText = resumeText || '';

    if (file) {
      const allowedExtensions = ['.pdf', '.doc', '.docx'];
      const fileExtension = extname(file.originalname).toLowerCase();

      if (!allowedExtensions.includes(fileExtension)) {
        const tempPath = join(process.cwd(), 'uploads', file.filename);
        if (fs.existsSync(tempPath)) {
          fs.unlinkSync(tempPath);
        }
        throw new Error('Invalid file type. Only PDF and Word documents are allowed.');
      }

      // Delete old resume file if it exists
      if (candidate.resume) {
        const oldFilePath = join(process.cwd(), 'uploads', candidate.resume);
        try {
          if (fs.existsSync(oldFilePath)) {
            fs.unlinkSync(oldFilePath);
          }
        } catch (err) {
          console.error(`Error deleting old resume file: ${candidate.resume}`, err);
        }
      }

      resumeFilename = file.filename;

      // Extract text synchronously if not provided
      if (!resumeText) {
        const filePath = join(process.cwd(), 'uploads', file.filename);
        try {
          if (fs.existsSync(filePath)) {
            const buffer = fs.readFileSync(filePath);
            if (fileExtension === '.pdf') {
              const outputDir = join(process.cwd(), 'uploads');
              const htmlFileName = file.filename.replace(/\.pdf$/i, '.html');
              const htmlFilePath = join(outputDir, htmlFileName);

              try {
                const command = `pdftohtml -s -noframes -c -dataurls "${filePath}" "${htmlFilePath}"`;
                execSync(command);

                if (fs.existsSync(htmlFilePath)) {
                  const rawHtml = fs.readFileSync(htmlFilePath, 'utf8');
                  extractedText = cleanPdftohtmlOutline(rawHtml);
                  fs.unlinkSync(htmlFilePath);
                  console.log(`[Sync Extract] pdftohtml conversion succeeded for candidate ID: ${id}`);
                }
              } catch (execError) {
                console.error('[Sync Extract] pdftohtml conversion failed:', execError.message);
              }
            } else if (fileExtension === '.docx' || fileExtension === '.doc') {
              const outputDir = join(process.cwd(), 'uploads');
              const htmlFileName = file.filename.replace(/\.(docx|doc)$/i, '.html');
              const htmlFilePath = join(outputDir, htmlFileName);

              try {
                const command = `libreoffice --headless --convert-to html --outdir "${outputDir}" "${filePath}"`;
                execSync(command);

                if (fs.existsSync(htmlFilePath)) {
                  extractedText = fs.readFileSync(htmlFilePath, 'utf8');
                  fs.unlinkSync(htmlFilePath);
                  console.log(`[Sync Extract] LibreOffice Word-to-HTML conversion succeeded for candidate ID: ${id}`);
                }
              } catch (libreOfficeError) {
                console.warn('[Sync Extract] LibreOffice conversion failed, falling back to Mammoth:', libreOfficeError.message);
                try {
                  const result = await mammoth.convertToHtml({ buffer });
                  extractedText = result.value || '';
                } catch (mammothError) {
                  console.error('[Sync Extract] Fallback Mammoth DOCX conversion failed:', mammothError);
                }
              }
            }
          }
        } catch (err) {
          console.error('Error extracting text during resume update:', err);
        }
      }
    } else if (resumeText) {
      // Generate premium PDF directly from edited HTML using LibreOffice
      const tempHtmlName = `temp-${id}-${Date.now()}.html`;
      const tempHtmlPath = join(process.cwd(), 'uploads', tempHtmlName);

      // Add clean styles to ensure beautiful styling when converting html to pdf
      const styledHtml = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <style>
            @page {
              size: A4;
              margin: 1.2in 1in 1.2in 1in;
            }
            body {
              font-family: Arial, Helvetica, sans-serif;
              line-height: 1.35;
              color: #2b2b2b;
              font-size: 11pt;
            }
            p { margin-top: 0; margin-bottom: 6px; }
            h1, h2, h3, h4, h5, h6 { 
              margin-top: 14px; 
              margin-bottom: 6px; 
              color: #111111;
              font-weight: bold;
            }
            h1 { font-size: 20pt; text-align: center; margin-bottom: 12px; }
            h2 { font-size: 14pt; border-bottom: 1.5px solid #4a5568; padding-bottom: 3px; margin-top: 18px; }
            h3 { font-size: 12pt; }
            table { 
              width: 100%; 
              border-collapse: collapse; 
              margin-top: 4px; 
              margin-bottom: 8px; 
              page-break-inside: avoid;
            }
            td { 
              padding: 2px 4px; 
              vertical-align: top; 
            }
            ul, ol { margin-top: 4px; margin-bottom: 6px; padding-left: 20px; }
            li { margin-bottom: 3px; }
          </style>
        </head>
        <body>
          ${resumeText}
        </body>
        </html>
      `;

      fs.writeFileSync(tempHtmlPath, styledHtml);

      try {
        const outputDir = join(process.cwd(), 'uploads');
        const pdfFileName = `resume-${id}-${Date.now()}.pdf`;
        const tempPdfPath = join(outputDir, tempHtmlName.replace(/\.html$/i, '.pdf'));

        const command = `libreoffice --headless --convert-to pdf --outdir "${outputDir}" "${tempHtmlPath}"`;
        execSync(command);

        if (fs.existsSync(tempHtmlPath)) {
          fs.unlinkSync(tempHtmlPath);
        }

        if (fs.existsSync(tempPdfPath)) {
          const finalPdfPath = join(outputDir, pdfFileName);
          fs.renameSync(tempPdfPath, finalPdfPath);
          resumeFilename = pdfFileName;

          // Delete old resume file if it exists
          if (candidate.resume) {
            const oldFilePath = join(process.cwd(), 'uploads', candidate.resume);
            try {
              if (fs.existsSync(oldFilePath)) {
                fs.unlinkSync(oldFilePath);
              }
            } catch (err) {
              console.error(`Error deleting old resume file: ${candidate.resume}`, err);
            }
          }
          console.log(`[Backend PDF Gen] PDF generated successfully for candidate ID: ${id}`);
        }
      } catch (err) {
        console.error('Error generating PDF from resumeText on server:', err);
        if (fs.existsSync(tempHtmlPath)) {
          fs.unlinkSync(tempHtmlPath);
        }
      }
    }

    // Update candidate's resume filename and text in the database
    const updatedCandidate = await this.prisma.candidate.update({
      where: { id },
      data: {
        resume: resumeFilename,
        resumeText: extractedText,
      },
      include: {
        skills: true,
        job: true,
      },
    });

    return updatedCandidate;
  }
}

function cleanPdftohtmlOutline(html: string): string {
  if (!html) return html;
  // Strip <hr/> and the Document Outline section
  let cleaned = html.replace(/<hr\s*\/?>\s*<a\s+name="outline">[\s\S]*?(<\/body>|<\/html>|$)/i, "$1");
  cleaned = cleaned.replace(/<a\s+name="outline">[\s\S]*?(<\/body>|<\/html>|$)/i, "$1");
  cleaned = cleaned.replace(/<h1>Document Outline<\/h1>[\s\S]*?(<\/body>|<\/html>|$)/i, "$1");
  return cleaned;
}

