"use client";

import React, { useState, useEffect, useRef } from "react";
import { useEditor, EditorContent, Editor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Paragraph from "@tiptap/extension-paragraph";
import Heading from "@tiptap/extension-heading";
import Underline from "@tiptap/extension-underline";
import Link from "@tiptap/extension-link";
import TextAlign from "@tiptap/extension-text-align";
import { TextStyle } from "@tiptap/extension-text-style";
import Color from "@tiptap/extension-color";
import { Table } from "@tiptap/extension-table";
import TableRow from "@tiptap/extension-table-row";
import TableCell from "@tiptap/extension-table-cell";
import TableHeader from "@tiptap/extension-table-header";
import Image from "@tiptap/extension-image";
import { Node, Mark } from "@tiptap/core";
import { 
  Undo2, 
  Redo2, 
  Bold, 
  Italic, 
  Underline as UnderlineIcon, 
  AlignLeft, 
  AlignCenter, 
  AlignRight, 
  AlignJustify, 
  List, 
  ListOrdered, 
  Link2, 
  Unlink, 
  PaintBucket, 
  Type, 
  Table2, 
  Plus, 
  Trash2, 
  ZoomIn, 
  ZoomOut,
  ChevronDown
} from "lucide-react";

interface CanvasResumeEditorProps {
  initialContent: string;
  styleHeader?: string;
  onChange: (combinedHtml: string) => void;
  zoom: number;
  onZoomChange: (zoom: number) => void;
}

// Helper to preserve PDF layout while normalizing nowrap text properties
export function cleanInlineStyleString(styleStr: string | null): string | null {
  if (!styleStr) return null;
  let cleaned = styleStr
    .replace(/position\s*:\s*absolute;?/gi, "position: relative;")
    .replace(/\btop\s*:\s*[^;"]+;?/gi, "")
    .replace(/\bleft\s*:\s*[^;"]+;?/gi, "")
    .replace(/white-space\s*:\s*nowrap;?/gi, "white-space: pre-wrap;");
  return cleaned.trim() || null;
}

// Helper to prepare parsed PDF HTML for smooth visual editing without empty pages, outline links, or huge vertical gaps
export function sanitizeResumeHtmlForEditor(html: string): string {
  if (!html) return "";
  let sanitized = html;

  // 1. Strip pdftohtml "Document Outline" section and bookmark links completely
  sanitized = sanitized.replace(/<hr\s*\/?>\s*<a\s+name="outline">[\s\S]*$/gi, "");
  sanitized = sanitized.replace(/<a\s+name="outline">[\s\S]*$/gi, "");
  sanitized = sanitized.replace(/<h1>Document Outline<\/h1>[\s\S]*$/gi, "");
  sanitized = sanitized.replace(/<a\s+href="#\d+"[^>]*>[\s\S]*?<\/a>/gi, "");

  // 2. Remove empty page divs generated by pdftohtml that create blank stacked pages
  sanitized = sanitized.replace(
    /<div\s+id="page\d+-div"[^>]*>([\s\S]*?)<\/div>/gi,
    (match, innerContent) => {
      const textOnly = innerContent.replace(/<[^>]*>/g, "").replace(/\s+/g, "").trim();
      if (!textOnly && !innerContent.includes("<img")) {
        return "";
      }
      return match;
    }
  );

  // 3. Clean <style> blocks to allow pre-wrap
  sanitized = sanitized.replace(/<style\b[^>]*>([\s\S]*?)<\/style>/gi, (match, styleContent) => {
    const cleanedStyle = styleContent.replace(/white-space\s*:\s*nowrap/gi, "white-space: pre-wrap");
    return `<style>${cleanedStyle}</style>`;
  });

  // 4. Normalize white-space: nowrap in inline styles to pre-wrap
  sanitized = sanitized.replace(/white-space\s*:\s*nowrap/gi, "white-space: pre-wrap");

  return sanitized;
}

// Custom Node and Mark definitions to preserve all PDF layout styles & IDs
const CustomParagraph = Paragraph.extend({
  addAttributes() {
    return {
      style: {
        default: null,
        parseHTML: element => cleanInlineStyleString(element.getAttribute("style")),
        renderHTML: attributes => attributes.style ? { style: cleanInlineStyleString(attributes.style) } : {},
      },
      id: {
        default: null,
        parseHTML: element => element.getAttribute("id"),
        renderHTML: attributes => attributes.id ? { id: attributes.id } : {},
      },
      class: {
        default: null,
        parseHTML: element => element.getAttribute("class"),
        renderHTML: attributes => attributes.class ? { class: attributes.class } : {},
      }
    };
  },
  addKeyboardShortcuts() {
    return {
      Enter: () => {
        // If inside list item, perform list item split
        if (this.editor.isActive("bulletList") || this.editor.isActive("orderedList")) {
          return this.editor.commands.splitBlock();
        }
        // Seamless line break: move cursor directly to next line below without splitting block containers
        return this.editor.commands.setHardBreak();
      },
    };
  },
});

const CustomHeading = Heading.extend({
  addAttributes() {
    return {
      style: {
        default: null,
        parseHTML: element => cleanInlineStyleString(element.getAttribute("style")),
        renderHTML: attributes => attributes.style ? { style: cleanInlineStyleString(attributes.style) } : {},
      },
      id: {
        default: null,
        parseHTML: element => element.getAttribute("id"),
        renderHTML: attributes => attributes.id ? { id: attributes.id } : {},
      },
      class: {
        default: null,
        parseHTML: element => element.getAttribute("class"),
        renderHTML: attributes => attributes.class ? { class: attributes.class } : {},
      }
    };
  },
});

const CustomDiv = Node.create({
  name: "div",
  group: "block",
  content: "block*",
  defining: true,
  addAttributes() {
    return {
      style: {
        default: null,
        parseHTML: element => element.getAttribute("style"),
        renderHTML: attributes => attributes.style ? { style: attributes.style } : {},
      },
      id: {
        default: null,
        parseHTML: element => element.getAttribute("id"),
        renderHTML: attributes => attributes.id ? { id: attributes.id } : {},
      },
      class: {
        default: null,
        parseHTML: element => element.getAttribute("class"),
        renderHTML: attributes => attributes.class ? { class: attributes.class } : {},
      }
    };
  },
  parseHTML() {
    return [{ tag: "div" }];
  },
  renderHTML({ HTMLAttributes }) {
    return ["div", HTMLAttributes, 0];
  },
});

const CustomSpan = Mark.create({
  name: "span",
  priority: 80,          // higher than TextStyle (50) so badge spans are parsed first
  spanning: true,
  addAttributes() {
    return {
      style: {
        default: null,
        parseHTML: element => element.getAttribute("style"),
        renderHTML: attributes => attributes.style ? { style: attributes.style } : {},
      },
      id: {
        default: null,
        parseHTML: element => element.getAttribute("id"),
        renderHTML: attributes => attributes.id ? { id: attributes.id } : {},
      },
      class: {
        default: null,
        parseHTML: element => element.getAttribute("class"),
        renderHTML: attributes => attributes.class ? { class: attributes.class } : {},
      }
    };
  },
  parseHTML() {
    return [{ tag: "span" }];
  },
  renderHTML({ HTMLAttributes }) {
    return ["span", HTMLAttributes, 0];
  },
});

const CustomImage = Image.extend({
  inline: true,
  group: "inline",
  addAttributes() {
    return {
      ...this.parent?.(),
      style: {
        default: null,
        parseHTML: element => element.getAttribute("style"),
        renderHTML: attributes => attributes.style ? { style: attributes.style } : {},
      },
      class: {
        default: null,
        parseHTML: element => element.getAttribute("class"),
        renderHTML: attributes => attributes.class ? { class: attributes.class } : {},
      }
    };
  },
});

const BackgroundImage = Node.create({
  name: "backgroundImage",
  group: "block",
  inline: false,
  draggable: false,
  priority: 100,
  addAttributes() {
    return {
      src: {
        default: null,
        parseHTML: element => element.getAttribute("src"),
        renderHTML: attributes => attributes.src ? { src: attributes.src } : {},
      },
      alt: {
        default: null,
        parseHTML: element => element.getAttribute("alt"),
        renderHTML: attributes => attributes.alt ? { alt: attributes.alt } : {},
      },
      width: {
        default: null,
        parseHTML: element => element.getAttribute("width"),
        renderHTML: attributes => attributes.width ? { width: attributes.width } : {},
      },
      height: {
        default: null,
        parseHTML: element => element.getAttribute("height"),
        renderHTML: attributes => attributes.height ? { height: attributes.height } : {},
      },
      style: {
        default: null,
        parseHTML: element => element.getAttribute("style"),
        renderHTML: attributes => attributes.style ? { style: attributes.style } : {},
      },
      class: {
        default: null,
        parseHTML: element => element.getAttribute("class"),
        renderHTML: attributes => attributes.class ? { class: attributes.class } : {},
      }
    };
  },
  parseHTML() {
    return [{ tag: "img.page-background-img" }];
  },
  renderHTML({ HTMLAttributes }) {
    return ["img", HTMLAttributes];
  },
});


// JSON fallback parser to support older data schema, if any
export function jsonToHtml(jsonStr: string): string {
  try {
    const data = JSON.parse(jsonStr);
    if (typeof data === "string") return data;
    return jsonStr;
  } catch (e) {
    return jsonStr;
  }
}

const fonts = [
  { label: "Default Font", value: "" },
  { label: "Arial", value: "Arial, sans-serif" },
  { label: "Times New Roman", value: "'Times New Roman', Times, serif" },
  { label: "Georgia", value: "Georgia, serif" },
  { label: "Courier New", value: "'Courier New', Courier, monospace" },
  { label: "Verdana", value: "Verdana, Geneva, sans-serif" },
  { label: "Inter", value: "Inter, sans-serif" },
];

const fontSizes = [
  { label: "10", value: "10px" },
  { label: "11", value: "11px" },
  { label: "12", value: "12px" },
  { label: "13", value: "13px" },
  { label: "14", value: "14px" },
  { label: "15", value: "15px" },
  { label: "16", value: "16px" },
  { label: "18", value: "18px" },
  { label: "20", value: "20px" },
  { label: "24", value: "24px" },
];

const colors = [
  "#000000", "#374151", "#5b21b6", "#1e40af", "#065f46", "#92400e", "#991b1b", "#86198f"
];

const highlights = [
  "transparent", "#fef08a", "#bbf7d0", "#bfdbfe", "#fbcfe8", "#ddd6fe", "#ffedd5"
];

const lineSpacings = [
  { label: "Single", value: "1" },
  { label: "1.15", value: "1.15" },
  { label: "1.3", value: "1.3" },
  { label: "1.5", value: "1.5" },
  { label: "Double", value: "2" },
];

export default function CanvasResumeEditor({ 
  initialContent, 
  styleHeader = "",
  onChange, 
  zoom, 
  onZoomChange 
}: CanvasResumeEditorProps) {
  const isLoadedRef = useRef(false);
  const [showTableMenu, setShowTableMenu] = useState(false);

  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        paragraph: false,
        heading: false,
      }),
      CustomParagraph,
      CustomHeading,
      CustomDiv,
      CustomSpan,
      CustomImage,
      BackgroundImage,
      Underline,
      Link.configure({ openOnClick: false }),
      TextAlign.configure({ types: ["heading", "paragraph"] }),
      TextStyle,
      Color,
      Table.configure({
        resizable: true,
      }),
      TableRow,
      TableHeader,
      TableCell,
    ],
    content: "",
    onUpdate({ editor }) {
      onChange(editor.getHTML());
    },
  });

  // Load content once when editor is ready
  useEffect(() => {
    if (editor && initialContent && !isLoadedRef.current) {
      const sanitized = sanitizeResumeHtmlForEditor(initialContent);
      editor.commands.setContent(sanitized);
      isLoadedRef.current = true;
    }
  }, [editor, initialContent]);

  if (!editor) return null;

  // Modify inline style attribute of current selection (e.g. font family, size, background color)
  const applyInlineStyle = (propName: string, propValue: string) => {
    const currentAttrs = editor.getAttributes("span");
    const oldStyle = currentAttrs.style || "";
    const stylesObj: Record<string, string> = {};
    
    oldStyle.split(";").forEach((p: string) => {
      const [k, v] = p.split(":").map(s => s.trim());
      if (k && v) stylesObj[k] = v;
    });

    if (propValue === "transparent" || propValue === "inherit" || !propValue) {
      delete stylesObj[propName];
    } else {
      stylesObj[propName] = propValue;
    }

    const newStyleStr = Object.entries(stylesObj)
      .map(([k, v]) => `${k}: ${v}`)
      .join("; ");

    if (newStyleStr) {
      editor.chain().focus().setMark("span", { style: newStyleStr }).run();
    } else {
      editor.chain().focus().unsetMark("span").run();
    }
  };

  // Modify block style attribute of selected blocks (e.g. line height)
  const applyBlockStyle = (propName: string, propValue: string) => {
    const { selection } = editor.state;
    editor.state.doc.nodesBetween(selection.from, selection.to, (node, pos) => {
      if (node.type.name === 'paragraph' || node.type.name === 'heading') {
        const oldStyle = node.attrs.style || "";
        const stylesObj: Record<string, string> = {};
        oldStyle.split(";").forEach((p: string) => {
          const [k, v] = p.split(":").map(s => s.trim());
          if (k && v) stylesObj[k] = v;
        });

        if (!propValue) {
          delete stylesObj[propName];
        } else {
          stylesObj[propName] = propValue;
        }

        const newStyleStr = Object.entries(stylesObj)
          .map(([k, v]) => `${k}: ${v}`)
          .join("; ");

        editor.chain().updateAttributes(node.type.name, { style: newStyleStr }).run();
      }
    });
  };

  const insertLink = () => {
    const previousUrl = editor.getAttributes("link").href;
    const url = window.prompt("Enter URL:", previousUrl);
    if (url === null) return;
    if (url === "") {
      editor.chain().focus().extendMarkRange("link").unsetLink().run();
      return;
    }
    editor.chain().focus().extendMarkRange("link").setLink({ href: url }).run();
  };

  const hasPages = initialContent
    ? (initialContent.includes("page1-div") || initialContent.includes("position:absolute") || initialContent.includes("class=\"pf\""))
    : false;

  const wrapperClass = hasPages
    ? "w-auto bg-transparent border-none shadow-none p-0 text-gray-900 dark:text-gray-100 transition-all duration-200 ease-out"
    : "w-full max-w-[816px] min-h-[1056px] bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-sm shadow-2xl p-4 sm:p-8 md:p-[1.2in] text-gray-900 dark:text-gray-100 transition-all duration-200 ease-out box-border mx-auto overflow-x-auto";

  return (
    <div className="flex flex-col h-full bg-gray-50 dark:bg-gray-950 border border-gray-200 dark:border-gray-800 rounded-2xl overflow-hidden shadow-inner">
      {/* Top Sticky Toolbar */}
      <div className="sticky top-0 z-20 flex items-center justify-between gap-2 p-2 sm:p-3 bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800 shadow-xs max-w-full overflow-hidden">
        <div className="flex items-center gap-1.5 overflow-x-auto no-scrollbar py-0.5 max-w-full">
          {/* History */}
          <button
            onClick={() => editor.chain().focus().undo().run()}
            disabled={!editor.can().undo()}
            title="Undo (Ctrl+Z)"
            className="p-2 text-gray-650 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800 rounded-lg transition-all disabled:opacity-40"
          >
            <Undo2 className="w-4 h-4" />
          </button>
          <button
            onClick={() => editor.chain().focus().redo().run()}
            disabled={!editor.can().redo()}
            title="Redo (Ctrl+Y)"
            className="p-2 text-gray-650 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800 rounded-lg transition-all disabled:opacity-40"
          >
            <Redo2 className="w-4 h-4" />
          </button>

          <div className="w-[1px] h-5 bg-gray-200 dark:bg-gray-800 mx-1" />

          {/* Heading Style Selector */}
          <select
            onChange={(e) => {
              const val = e.target.value;
              if (val === "p") {
                editor.chain().focus().setParagraph().run();
              } else {
                editor.chain().focus().toggleHeading({ level: Number(val) as 1 | 2 | 3 }).run();
              }
            }}
            value={
              editor.isActive("heading", { level: 1 }) ? "1" :
              editor.isActive("heading", { level: 2 }) ? "2" :
              editor.isActive("heading", { level: 3 }) ? "3" : "p"
            }
            className="px-2.5 py-1.5 bg-gray-50 dark:bg-gray-800 text-xs font-semibold text-gray-700 dark:text-gray-200 rounded-lg border border-gray-200 dark:border-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            <option value="p">Normal Text</option>
            <option value="1">Heading 1</option>
            <option value="2">Heading 2</option>
            <option value="3">Heading 3</option>
          </select>

          {/* Fonts Selector */}
          <select
            onChange={(e) => applyInlineStyle("font-family", e.target.value)}
            className="px-2.5 py-1.5 bg-gray-50 dark:bg-gray-800 text-xs font-semibold text-gray-700 dark:text-gray-200 rounded-lg border border-gray-200 dark:border-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            {fonts.map(font => (
              <option key={font.label} value={font.value}>{font.label}</option>
            ))}
          </select>

          {/* Font Size Selector */}
          <select
            onChange={(e) => applyInlineStyle("font-size", e.target.value)}
            className="px-2.5 py-1.5 bg-gray-50 dark:bg-gray-800 text-xs font-semibold text-gray-700 dark:text-gray-200 rounded-lg border border-gray-200 dark:border-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-500"
            defaultValue="14px"
          >
            {fontSizes.map(sz => (
              <option key={sz.label} value={sz.value}>{sz.label}</option>
            ))}
          </select>

          <div className="w-[1px] h-5 bg-gray-200 dark:bg-gray-800 mx-1" />

          {/* Text Formatting */}
          <button
            onClick={() => editor.chain().focus().toggleBold().run()}
            className={`p-2 rounded-lg transition-all ${editor.isActive("bold") ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-650 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Bold (Ctrl+B)"
          >
            <Bold className="w-4 h-4" />
          </button>
          <button
            onClick={() => editor.chain().focus().toggleItalic().run()}
            className={`p-2 rounded-lg transition-all ${editor.isActive("italic") ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-650 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Italic (Ctrl+I)"
          >
            <Italic className="w-4 h-4" />
          </button>
          <button
            onClick={() => editor.chain().focus().toggleUnderline().run()}
            className={`p-2 rounded-lg transition-all ${editor.isActive("underline") ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-650 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Underline (Ctrl+U)"
          >
            <UnderlineIcon className="w-4 h-4" />
          </button>

          {/* Text Color Picker */}
          <div className="relative group">
            <button
              title="Text Color"
              className="p-2 text-gray-655 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors flex items-center gap-1"
            >
              <PaintBucket className="w-4 h-4 text-violet-500" />
            </button>
            <div className="absolute top-full left-0 mt-1 hidden group-hover:flex flex-wrap gap-1.5 p-2.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl shadow-lg w-44 z-30">
              {colors.map(color => (
                <button
                  key={color}
                  onClick={() => editor.chain().focus().setColor(color).run()}
                  className="w-6 h-6 rounded-full border border-gray-200 hover:scale-110 active:scale-95 transition-all shadow-xs"
                  style={{ backgroundColor: color }}
                />
              ))}
              <button
                onClick={() => editor.chain().focus().unsetColor().run()}
                className="w-full text-[10px] py-1 border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-750 text-gray-600 dark:text-gray-300 rounded font-semibold mt-1"
              >
                Reset Color
              </button>
            </div>
          </div>

          {/* Highlight Color Picker */}
          <div className="relative group">
            <button
              title="Highlight Color"
              className="p-2 text-gray-655 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors flex items-center gap-1"
            >
              <PaintBucket className="w-4 h-4 text-yellow-500" />
            </button>
            <div className="absolute top-full left-0 mt-1 hidden group-hover:flex flex-wrap gap-1.5 p-2.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl shadow-lg w-44 z-30">
              {highlights.map(color => (
                <button
                  key={color}
                  onClick={() => applyInlineStyle("background-color", color)}
                  className="w-6 h-6 rounded-full border border-gray-200 hover:scale-110 active:scale-95 transition-all shadow-xs"
                  style={{ backgroundColor: color === "transparent" ? "white" : color, border: color === "transparent" ? "1px dashed #ccc" : "" }}
                />
              ))}
            </div>
          </div>

          <div className="w-[1px] h-5 bg-gray-200 dark:bg-gray-800 mx-1" />

          {/* Alignments */}
          <button
            onClick={() => editor.chain().focus().setTextAlign("left").run()}
            className={`p-2 rounded-lg transition-all ${editor.isActive({ textAlign: "left" }) ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-655 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Align Left"
          >
            <AlignLeft className="w-4 h-4" />
          </button>
          <button
            onClick={() => editor.chain().focus().setTextAlign("center").run()}
            className={`p-2 rounded-lg transition-all ${editor.isActive({ textAlign: "center" }) ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-655 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Align Center"
          >
            <AlignCenter className="w-4 h-4" />
          </button>
          <button
            onClick={() => editor.chain().focus().setTextAlign("right").run()}
            className={`p-2 rounded-lg transition-all ${editor.isActive({ textAlign: "right" }) ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-655 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Align Right"
          >
            <AlignRight className="w-4 h-4" />
          </button>
          <button
            onClick={() => editor.chain().focus().setTextAlign("justify").run()}
            className={`p-2 rounded-lg transition-all ${editor.isActive({ textAlign: "justify" }) ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-655 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Justify"
          >
            <AlignJustify className="w-4 h-4" />
          </button>

          <div className="w-[1px] h-5 bg-gray-200 dark:bg-gray-800 mx-1" />

          {/* Lists */}
          <button
            onClick={() => editor.chain().focus().toggleBulletList().run()}
            className={`p-2 rounded-lg transition-all ${editor.isActive("bulletList") ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-655 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Bullet List"
          >
            <List className="w-4 h-4" />
          </button>
          <button
            onClick={() => editor.chain().focus().toggleOrderedList().run()}
            className={`p-2 rounded-lg transition-all ${editor.isActive("orderedList") ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-655 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Numbered List"
          >
            <ListOrdered className="w-4 h-4" />
          </button>

          <div className="w-[1px] h-5 bg-gray-200 dark:bg-gray-800 mx-1" />

          {/* Line Spacing */}
          <select
            onChange={(e) => applyBlockStyle("line-height", e.target.value)}
            className="px-2.5 py-1.5 bg-gray-50 dark:bg-gray-800 text-xs font-semibold text-gray-700 dark:text-gray-200 rounded-lg border border-gray-200 dark:border-gray-700 focus:outline-none focus:ring-1 focus:ring-blue-500"
            defaultValue="1.15"
          >
            {lineSpacings.map(spacing => (
              <option key={spacing.label} value={spacing.value}>{spacing.label} Line Spacing</option>
            ))}
          </select>

          <div className="w-[1px] h-5 bg-gray-200 dark:bg-gray-800 mx-1" />

          {/* Links */}
          <button
            onClick={insertLink}
            className={`p-2 rounded-lg transition-all ${editor.isActive("link") ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-655 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
            title="Insert Link"
          >
            <LinkIcon2 className="w-4 h-4" />
          </button>

          {/* Table Dropdown Menu */}
          <div className="relative">
            <button
              onClick={() => setShowTableMenu(!showTableMenu)}
              className={`p-2 rounded-lg transition-all flex items-center gap-1 ${editor.isActive("table") ? "bg-blue-100 text-blue-700 dark:bg-blue-900/60 dark:text-blue-200" : "text-gray-655 hover:bg-gray-100 dark:text-gray-350 dark:hover:bg-gray-800"}`}
              title="Table Actions"
            >
              <Table2 className="w-4 h-4" />
              <ChevronDown className="w-3.5 h-3.5 opacity-60" />
            </button>
            
            {showTableMenu && (
              <div 
                className="absolute top-full left-0 mt-1 flex flex-col p-1.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl shadow-lg w-48 z-30"
                onMouseLeave={() => setShowTableMenu(false)}
              >
                <button
                  onClick={() => {
                    editor.chain().focus().insertTable({ rows: 3, cols: 3, withHeaderRow: false }).run();
                    setShowTableMenu(false);
                  }}
                  className="flex items-center gap-2 px-3 py-2 text-xs text-left text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-750 rounded-lg font-semibold"
                >
                  <Plus className="w-3.5 h-3.5 text-emerald-500" /> Insert Table
                </button>
                <div className="h-[1px] bg-gray-150 dark:bg-gray-750 my-1" />
                <button
                  onClick={() => {
                    editor.chain().focus().addRowBefore().run();
                    setShowTableMenu(false);
                  }}
                  disabled={!editor.isActive("table")}
                  className="flex items-center gap-2 px-3 py-2 text-xs text-left text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-750 rounded-lg font-semibold disabled:opacity-40"
                >
                  Add Row Above
                </button>
                <button
                  onClick={() => {
                    editor.chain().focus().addRowAfter().run();
                    setShowTableMenu(false);
                  }}
                  disabled={!editor.isActive("table")}
                  className="flex items-center gap-2 px-3 py-2 text-xs text-left text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-750 rounded-lg font-semibold disabled:opacity-40"
                >
                  Add Row Below
                </button>
                <button
                  onClick={() => {
                    editor.chain().focus().addColumnBefore().run();
                    setShowTableMenu(false);
                  }}
                  disabled={!editor.isActive("table")}
                  className="flex items-center gap-2 px-3 py-2 text-xs text-left text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-750 rounded-lg font-semibold disabled:opacity-40"
                >
                  Add Column Left
                </button>
                <button
                  onClick={() => {
                    editor.chain().focus().addColumnAfter().run();
                    setShowTableMenu(false);
                  }}
                  disabled={!editor.isActive("table")}
                  className="flex items-center gap-2 px-3 py-2 text-xs text-left text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-750 rounded-lg font-semibold disabled:opacity-40"
                >
                  Add Column Right
                </button>
                <div className="h-[1px] bg-gray-150 dark:bg-gray-750 my-1" />
                <button
                  onClick={() => {
                    editor.chain().focus().deleteRow().run();
                    setShowTableMenu(false);
                  }}
                  disabled={!editor.isActive("table")}
                  className="flex items-center gap-2 px-3 py-2 text-xs text-left text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/20 rounded-lg font-semibold disabled:opacity-40"
                >
                  <Trash2 className="w-3.5 h-3.5" /> Delete Row
                </button>
                <button
                  onClick={() => {
                    editor.chain().focus().deleteColumn().run();
                    setShowTableMenu(false);
                  }}
                  disabled={!editor.isActive("table")}
                  className="flex items-center gap-2 px-3 py-2 text-xs text-left text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/20 rounded-lg font-semibold disabled:opacity-40"
                >
                  <Trash2 className="w-3.5 h-3.5" /> Delete Column
                </button>
                <button
                  onClick={() => {
                    editor.chain().focus().deleteTable().run();
                    setShowTableMenu(false);
                  }}
                  disabled={!editor.isActive("table")}
                  className="flex items-center gap-2 px-3 py-2 text-xs text-left text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/20 rounded-lg font-semibold disabled:opacity-40"
                >
                  <Trash2 className="w-3.5 h-3.5" /> Delete Table
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Zoom Controls */}
        <div className="flex items-center gap-1.5 bg-gray-100 dark:bg-gray-800 px-2.5 py-1 rounded-xl shrink-0">
          <button
            onClick={() => onZoomChange(Math.max(0.5, zoom - 0.1))}
            className="p-1 hover:bg-white dark:hover:bg-gray-700 rounded-lg shadow-2xs text-gray-650 dark:text-gray-250 transition-all"
            title="Zoom Out"
          >
            <ZoomOut className="w-3.5 h-3.5" />
          </button>
          <span className="text-[11px] font-bold w-10 text-center text-gray-700 dark:text-gray-300">
            {Math.round(zoom * 100)}%
          </span>
          <button
            onClick={() => onZoomChange(Math.min(1.5, zoom + 0.1))}
            className="p-1 hover:bg-white dark:hover:bg-gray-700 rounded-lg shadow-2xs text-gray-655 dark:text-gray-250 transition-all"
            title="Zoom In"
          >
            <ZoomIn className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Main Pages Canvas Container */}
      <div className="flex-1 overflow-auto p-2 sm:p-6 flex flex-col items-center bg-gray-100 dark:bg-gray-950/70" style={{ minWidth: 0 }}>
        <div
          style={{
            transform: `scale(${zoom})`,
            transformOrigin: "top center",
            transition: "transform 0.15s ease-out",
          }}
          className={wrapperClass}
        >
          {/* Injecting Editor specific styling for visual table lines & spacing rules */}
          <style>{`
            /* ================================================================
               RESUME EDITOR  —  Production-grade CSS
               Design principle: Inline styles from the PDF WIN.
               This sheet only provides page chrome & structural scaffolding.
               Nothing here uses !important on typography properties.
            ================================================================ */

            /* 1. Editor root — no font-size/family override, force text wrapping */
            .ProseMirror {
              outline: none;
              caret-color: #2563eb;
              overflow-wrap: anywhere !important;
              word-break: break-word !important;
              white-space: pre-wrap !important;
            }

            /* Force all editable text blocks to wrap cleanly without stripping layout */
            .ProseMirror p,
            .ProseMirror h1, .ProseMirror h2, .ProseMirror h3,
            .ProseMirror h4, .ProseMirror h5, .ProseMirror h6,
            .ProseMirror li {
              white-space: pre-wrap !important;
              word-break: break-word !important;
              overflow-wrap: anywhere !important;
              max-width: 100% !important;
              box-sizing: border-box !important;
              z-index: 2 !important;
            }

            /* Ensure inner text spans wrap properly */
            .ProseMirror p span,
            .ProseMirror li span,
            .ProseMirror h1 span, .ProseMirror h2 span, .ProseMirror h3 span {
              white-space: pre-wrap !important;
              word-break: break-word !important;
              overflow-wrap: anywhere !important;
            }

            /* 2. A4 page container — chrome only */
            .ProseMirror div[id$="-div"],
            .ProseMirror .pf,
            .ProseMirror .resume-page {
              position: relative !important;
              box-sizing: border-box !important;
              width: 794px !important;      /* A4 @ 96dpi */
              min-height: 1123px !important; /* A4 @ 96dpi */
              margin: 32px auto !important;
              padding: 56px 64px !important;
              background: #ffffff !important;
              box-shadow: 0 2px 16px 0 rgba(0,0,0,0.13), 0 0 0 1px rgba(0,0,0,0.06) !important;
              border-radius: 3px !important;
              overflow: visible !important;
            }

            /* 3. Template resumes (have a background image) — no padding */
            .ProseMirror div[id$="-div"].has-bg-img,
            .ProseMirror .pf.has-bg-img,
            .ProseMirror .resume-page.has-bg-img {
              padding: 0 !important;
            }

            /* 4. Dark mode page chrome */
            .dark .ProseMirror div[id$="-div"],
            .dark .ProseMirror .pf,
            .dark .ProseMirror .resume-page {
              background: #1e293b !important;
              box-shadow: 0 2px 24px 0 rgba(0,0,0,0.45) !important;
            }

            /* 5. Background template image — fills page absolutely */
            .ProseMirror img.page-background-img {
              position: absolute !important;
              inset: 0 !important;
              width: 100% !important;
              height: 100% !important;
              z-index: 0 !important;
              pointer-events: none !important;
              display: block !important;
              object-fit: fill !important;
            }

            /* 6. Direct children of page sit above background image */
            .ProseMirror div[id$="-div"] > *:not(.page-background-img),
            .ProseMirror .pf > *:not(.page-background-img),
            .ProseMirror .resume-page > *:not(.page-background-img) {
              position: relative;
              z-index: 1;
            }

            /* 7. Skill badge spans — keep their inline-block display */
            .ProseMirror span[style*="border-radius"],
            .ProseMirror span[style*="background-color"],
            .ProseMirror span[style*="padding"] {
              display: inline-block;
              white-space: nowrap;
            }

            /* 8. Content images — never become block-level */
            .ProseMirror img:not(.page-background-img) {
              display: inline-block;
              max-width: 100%;
              position: relative;
              z-index: 2;
            }

            /* 9. Two-column layout table — no visible borders */
            .ProseMirror table {
              border-collapse: collapse;
              width: 100%;
              table-layout: fixed;
              border: none;
            }
            .ProseMirror table td,
            .ProseMirror table th {
              border: none;
              vertical-align: top;
              padding: 0;
            }

            /* 10. Lists — preserve indentation */
            .ProseMirror ul,
            .ProseMirror ol {
              padding-left: 20px;
              margin: 2px 0 4px 0;
            }
            .ProseMirror li {
              margin-bottom: 2px;
            }

            /* 11. HR dividers */
            .ProseMirror hr {
              border: none;
              border-top: 1px solid #94a3b8;
              margin: 6px 0;
            }

            /* 12. Paragraph & heading defaults — minimal, won't override inline styles */
            .ProseMirror p {
              margin: 0 0 2px 0;
            }
            .ProseMirror h2,
            .ProseMirror h3,
            .ProseMirror h4 {
              margin: 8px 0 4px 0;
            }

            /* 13. Dark mode text fallback */
            .dark .ProseMirror h2,
            .dark .ProseMirror h3 {
              color: #f1f5f9;
            }

            /* 14. Pass-through for any injected PDF stylesheet */
            ${styleHeader}
          `}</style>
          <EditorContent editor={editor} />
        </div>
      </div>
    </div>
  );
}

// Named alias mapping for Lucide Link icon to prevent conflicts with nextjs/react-router Link component
function LinkIcon2(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  );
}
