/*
 * pdfToHtmlConverter.ts
 * -------------------------------------------------
 * This module provides two core functions used throughout the
 * ResumePortal frontend to transform PDF conversion output (HTML)
 * into a format suitable for the Quill rich‑text editor.
 *
 * 1. `parsePlainTextToHtml` – Converts plain‑text resume strings
 *    (e.g., extracted via OCR) into minimal HTML with headings,
 *    paragraphs, ordered & unordered lists.
 *
 * 2. `cleanPdftohtmlForEditor` – Takes the raw HTML generated by
 *    the `pdftohtml` tool (which includes absolute positioned <p>
 *    elements and style classes) and produces a clean, structured
 *    HTML string that retains headings, lists and basic formatting.
 *
 * Both functions are pure and have no external dependencies, making
 * them easy to unit‑test and reuse.
 */

/**
 * Convert plain‑text resume content into HTML.
 * Handles bullet points, numbered lists, and simple headings.
 */
export function parsePlainTextToHtml(text: string): string {
  if (!text) return "";

  const lines = text.split(/\r?\n/);
  let html = "";
  let listType: "bullet" | "ordered" | null = null;

  for (let line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      // End any open list and insert a line break paragraph.
      if (listType === "bullet") {
        html += "</ul>";
        listType = null;
      } else if (listType === "ordered") {
        html += "</ol>";
        listType = null;
      }
      html += "<p><br></p>";
      continue;
    }

    // Skip typical footer / page markers.
    const isFooter = /^--\s*\d+\s*of\s*\d+\s*--$/i.test(trimmed) || /^page\s*\d+/i.test(trimmed);
    if (isFooter) continue;

    const bulletMatch = trimmed.match(/^[•*\-\u2022]\s*(.*)/);
    const numberMatch = trimmed.match(/^(\d+)[\.)]\s*(.*)/);

    if (bulletMatch) {
      if (listType === "ordered") {
        html += "</ol>";
        listType = null;
      }
      if (!listType) {
        html += "<ul>";
        listType = "bullet";
      }
      html += `<li>${bulletMatch[1]}</li>`;
    } else if (numberMatch) {
      if (listType === "bullet") {
        html += "</ul>";
        listType = null;
      }
      if (!listType) {
        html += "<ol>";
        listType = "ordered";
      }
      html += `<li>${numberMatch[2]}</li>`;
    } else {
      // Close any open list before a normal paragraph.
      if (listType === "bullet") {
        html += "</ul>";
        listType = null;
      } else if (listType === "ordered") {
        html += "</ol>";
        listType = null;
      }

      // Very short lines are treated as headings.
      const isHeader = trimmed.length < 50 && /^(Career Summary|Education|Skills|Experience|Projects|Certifications|Professional Experience|Work Experience|Summary of Qualifications)$/i.test(trimmed);
      if (isHeader) {
        html += `<h3>${trimmed}</h3>`;
      } else {
        html += `<p>${trimmed}</p>`;
      }
    }
  }

  // Close any list left open at EOF.
  if (listType === "bullet") html += "</ul>";
  else if (listType === "ordered") html += "</ol>";

  return html;
}

/**
 * Clean the HTML generated by `pdftohtml` so it can be safely pasted
 * into Quill. The function:
 *   • Parses inline style classes to discover font‑size and boldness.
 *   • Extracts absolute positioned <p> elements and re‑orders them
 *     top‑to‑bottom (column‑aware when needed).
 *   • Detects headings, bullets and normal paragraphs and emits
 *     clean semantic tags (`<h3>`, `<ul>/<ol>`, `<p>`).
 */
export function cleanPdftohtmlForEditor(htmlStr: string): string {
  if (!htmlStr) return "";

  // Bail early if the HTML does not contain absolute positioning.
  if (!htmlStr.includes("position:absolute")) return htmlStr;

  // 1️⃣ Build a map of style class → {bold, fontSize}
  const styleMap: Record<string, { bold: boolean; fontSize: number }> = {};
  const styleRegex = /\.([\w-]+)\{([^}]+)\}/g;
  let styleMatch: RegExpExecArray | null;
  while ((styleMatch = styleRegex.exec(htmlStr)) !== null) {
    const className = styleMatch[1];
    const styleContent = styleMatch[2];
    styleMap[className] = {
      bold: /bold|Montserrat-SemiBold|Lora-Bold/.test(styleContent),
      fontSize: parseInt(styleContent.match(/font-size:(\d+)px/)?.[1] ?? "14", 10),
    };
  }

  // 2️⃣ Extract all <p> elements with their absolute coordinates.
  const pRegex = /<p\s+style="([^"]*)"\s+class="([^"]*)"[^>]*>([\s\S]*?)<\/p>/gi;
  const paragraphs: Array<{ top: number; left: number; text: string; fontSize: number; isBold: boolean; className: string }> = [];
  let pMatch: RegExpExecArray | null;
  while ((pMatch = pRegex.exec(htmlStr)) !== null) {
    const styleAttr = pMatch[1];
    const className = pMatch[2];
    const rawContent = pMatch[3];

    const top = parseInt(styleAttr.match(/top:(\d+)px/)?.[1] ?? "0", 10);
    const left = parseInt(styleAttr.match(/left:(\d+)px/)?.[1] ?? "0", 10);

    const cleanText = rawContent
      .replace(/<br\s*\/?\>/gi, "__BR__")
      .replace(/<[^>]*>/g, "")
      .replace(/__BR__/g, "<br/>")
      .replace(/&#160;/g, " ")
      .replace(/&nbsp;/g, " ")
      .trim();
    if (!cleanText) continue;

    const classInfo = styleMap[className] ?? { fontSize: 14, bold: false };
    const isBold = classInfo.bold || rawContent.includes("<b>") || rawContent.includes("<strong>");

    paragraphs.push({ top, left, text: cleanText, fontSize: classInfo.fontSize, isBold, className });
  }

  if (paragraphs.length === 0) return htmlStr;

  // 3️⃣ Detect potential two‑column layouts.
  const leftGroup = paragraphs.filter(p => p.left < 300);
  const rightGroup = paragraphs.filter(p => p.left >= 300);
  const hasColumns = leftGroup.length > 5 && rightGroup.length > 5;

  // Helper to sort & merge lines, then emit semantic blocks.
  const processColumn = (items: typeof paragraphs) => {
    items.sort((a, b) => {
      if (Math.abs(a.top - b.top) < 8) return a.left - b.left;
      return a.top - b.top;
    });

    const lines: typeof paragraphs[] = [];
    let currentLine: typeof paragraphs = [];
    for (const p of items) {
      if (!currentLine.length) {
        currentLine.push(p);
      } else if (Math.abs(p.top - currentLine[0].top) < 8) {
        currentLine.push(p);
      } else {
        lines.push(currentLine);
        currentLine = [p];
      }
    }
    if (currentLine.length) lines.push(currentLine);

    return lines.map(line => {
      const mergedText = line.map(p => p.text).join(" ");
      const maxFontSize = Math.max(...line.map(p => p.fontSize));
      const isHeader = maxFontSize > 18 || line.some(p => p.isBold && p.text.toUpperCase() === p.text && p.text.length < 50);
      const isBullet = line.some(p => /^[•\-\▪]/.test(p.text));
      const clean = mergedText.replace(/^[•\-\▪]\s*/, "").trim();

      if (isHeader) return `<h3><strong>${clean}</strong></h3>`;
      if (isBullet) return `<ul><li>${clean}</li></ul>`;
      return `<p>${clean}</p>`;
    });
  };

  const finalBlocks: string[] = [];
  if (hasColumns) {
    // Insert optional section titles – adjust as needed.
    finalBlocks.push("<h2><strong>CONTACT & PROFILE</strong></h2>");
    finalBlocks.push(...processColumn(leftGroup));
    finalBlocks.push("<hr/>");
    finalBlocks.push("<h2><strong>EXPERIENCE & HISTORY</strong></h2>");
    finalBlocks.push(...processColumn(rightGroup));
  } else {
    finalBlocks.push(...processColumn(paragraphs));
  }

  // Clean up stray closing tags that may appear when consecutive lists are generated.
  let resultHtml = finalBlocks.join("\n");
  resultHtml = resultHtml.replace(/<\/ul>\n<ul>/g, "\n");

  return resultHtml;
}
