/*
 * pdfToHtmlConverter.ts
 * -------------------------------------------------
 * This module provides two core functions used throughout the
 * ResumePortal frontend to transform PDF conversion output (HTML)
 * into a format suitable for the Quill/TipTap rich‑text editors.
 *
 * 1. `parsePlainTextToHtml` – Converts plain‑text resume strings
 *    (e.g., extracted via OCR) into minimal HTML with headings,
 *    paragraphs, ordered & unordered lists.
 *
 * 2. `cleanPdftohtmlForEditor` – Takes the raw HTML generated by
 *    the `pdftohtml` tool (which includes absolute positioned <p>
 *    elements and style classes) and produces a clean, structured
 *    HTML string that retains headings, lists and basic formatting
 *    while transforming coordinates into natural document flow (tables/lists).
 */

/**
 * Convert plain‑text resume content into HTML.
 * Handles bullet points, numbered lists, and simple headings.
 */
export function parsePlainTextToHtml(text: string): string {
  if (!text) return "";

  const lines = text.split(/\r?\n/);
  let html = "";
  let listType: "bullet" | "ordered" | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      // End any open list and insert a line break paragraph.
      if (listType === "bullet") {
        html += "</ul>";
        listType = null;
      } else if (listType === "ordered") {
        html += "</ol>";
        listType = null;
      }
      html += "<p><br></p>";
      continue;
    }

    // Skip typical footer / page markers.
    const isFooter = /^--\s*\d+\s*of\s*\d+\s*--$/i.test(trimmed) || /^page\s*\d+/i.test(trimmed);
    if (isFooter) continue;

    const bulletMatch = trimmed.match(/^[•*\-\u2022]\s*(.*)/);
    const numberMatch = trimmed.match(/^(\d+)[\.)]\s*(.*)/);

    if (bulletMatch) {
      if (listType === "ordered") {
        html += "</ol>";
        listType = null;
      }
      if (!listType) {
        html += "<ul>";
        listType = "bullet";
      }
      html += `<li>${bulletMatch[1]}</li>`;
    } else if (numberMatch) {
      if (listType === "bullet") {
        html += "</ul>";
        listType = null;
      }
      if (!listType) {
        html += "<ol>";
        listType = "ordered";
      }
      html += `<li>${numberMatch[2]}</li>`;
    } else {
      // Close any open list before a normal paragraph.
      if (listType === "bullet") {
        html += "</ul>";
        listType = null;
      } else if (listType === "ordered") {
        html += "</ol>";
        listType = null;
      }

      // Very short lines are treated as headings.
      const isHeader = trimmed.length < 50 && /^(Career Summary|Education|Skills|Experience|Projects|Certifications|Professional Experience|Work Experience|Summary of Qualifications)$/i.test(trimmed);
      if (isHeader) {
        html += `<h3>${trimmed}</h3>`;
      } else {
        html += `<p>${trimmed}</p>`;
      }
    }
  }

  // Close any list left open at EOF.
  if (listType === "bullet") html += "</ul>";
  else if (listType === "ordered") html += "</ol>";

  return html;
}

/**
 * Clean the HTML generated by `pdftohtml` so it can be safely pasted
 * into Quill/TipTap. The function:
 *   • Parses inline style classes to discover font‑size and boldness.
 *   • Extracts absolute positioned <p> elements and re‑orders them
 *     top‑to‑bottom (column‑aware when needed).
 *   • Translates absolute position attributes into natural HTML structure,
 *     converting side-by-side elements to semantic borderless table rows
 *     and bullets to actual lists.
 */
export function cleanPdftohtmlForEditor(htmlStr: string): string {
  if (!htmlStr) return "";

  // Bail early if the HTML does not contain absolute positioning.
  if (!htmlStr.includes("position:absolute")) return htmlStr;

  // 1️⃣ Build a map of style class → {bold, fontSize, rawStyles}
  const styleMap: Record<string, { bold: boolean; fontSize: number; rawStyles: string }> = {};
  const styleRegex = /\.([\w-]+)\{([^}]+)\}/g;
  let styleMatch: RegExpExecArray | null;
  while ((styleMatch = styleRegex.exec(htmlStr)) !== null) {
    const className = styleMatch[1];
    const styleContent = styleMatch[2];
    
    // Extract non-positioning style declarations to inline them if needed
    const cleanedStyles = styleContent.split(";")
      .map(s => s.trim())
      .filter(s => {
        const key = s.split(":")[0].trim().toLowerCase();
        return ![
          "position",
          "top",
          "left",
          "right",
          "bottom",
          "width",
          "height",
        ].includes(key);
      })
      .join("; ");

    styleMap[className] = {
      bold: /bold|Montserrat-SemiBold|Lora-Bold/.test(styleContent),
      fontSize: parseInt(styleContent.match(/font-size:(\d+)px/)?.[1] ?? "14", 10),
      rawStyles: cleanedStyles,
    };
  }

  // Helper to filter style attributes
  const cleanStyleAttr = (styleAttr: string): string => {
    return styleAttr
      .split(";")
      .map(s => s.trim())
      .filter(s => {
        const key = s.split(":")[0].trim().toLowerCase();
        return ![
          "position",
          "top",
          "left",
          "right",
          "bottom",
          "width",
          "height",
          "z-index",
        ].includes(key);
      })
      .join("; ") + ";";
  };

  // 2️⃣ Extract all <p> elements with their absolute coordinates.
  const pRegex = /<p\s+style="([^"]*)"\s+class="([^"]*)"[^>]*>([\s\S]*?)<\/p>/gi;
  const paragraphs: Array<{ 
    top: number; 
    left: number; 
    html: string; 
    fontSize: number; 
    isBold: boolean; 
    className: string;
    style: string;
  }> = [];
  
  let pMatch: RegExpExecArray | null;
  while ((pMatch = pRegex.exec(htmlStr)) !== null) {
    const styleAttr = pMatch[1];
    const className = pMatch[2];
    const rawContent = pMatch[3];

    const top = parseInt(styleAttr.match(/top:(\d+)px/)?.[1] ?? "0", 10);
    const left = parseInt(styleAttr.match(/left:(\d+)px/)?.[1] ?? "0", 10);

    const innerHtml = rawContent.trim();
    if (!innerHtml) continue;

    const plainText = innerHtml.replace(/<[^>]*>/g, "").trim();
    if (!plainText) continue;

    const classInfo = styleMap[className] ?? { fontSize: 14, bold: false, rawStyles: "" };
    const isBold = classInfo.bold || innerHtml.includes("<b>") || innerHtml.includes("<strong>");

    paragraphs.push({ 
      top, 
      left, 
      html: innerHtml, 
      fontSize: classInfo.fontSize, 
      isBold, 
      className,
      style: cleanStyleAttr(styleAttr),
    });
  }

  if (paragraphs.length === 0) return htmlStr;

  // 3️⃣ Group paragraphs into lines (horizontal rows)
  // Sort primarily by vertical coordinate (top)
  paragraphs.sort((a, b) => a.top - b.top);

  const lines: typeof paragraphs[] = [];
  let currentLine: typeof paragraphs = [];
  
  for (const p of paragraphs) {
    if (!currentLine.length) {
      currentLine.push(p);
    } else if (Math.abs(p.top - currentLine[0].top) < 8) {
      // Within vertical tolerance, group in same line
      currentLine.push(p);
    } else {
      lines.push(currentLine);
      currentLine = [p];
    }
  }
  if (currentLine.length) lines.push(currentLine);

  // Sort elements in each line horizontally (left-to-right) and merge close elements
  const finalLines: typeof paragraphs[] = [];
  for (const line of lines) {
    line.sort((a, b) => a.left - b.left);
    
    const mergedLine: typeof line = [];
    for (const p of line) {
      if (!mergedLine.length) {
        mergedLine.push(p);
      } else {
        const prev = mergedLine[mergedLine.length - 1];
        const prevTextLength = prev.html.replace(/<[^>]*>/g, "").trim().length;
        // Estimate width in pixels using 6px per character as standard average
        const prevWidth = prevTextLength * 6;
        const prevRight = prev.left + prevWidth;
        const gap = p.left - prevRight;
        
        if (gap < 40) {
          prev.html += " " + p.html;
          prev.fontSize = Math.max(prev.fontSize, p.fontSize);
          prev.isBold = prev.isBold || p.isBold;
        } else {
          mergedLine.push(p);
        }
      }
    }
    if (mergedLine.length > 0) {
      finalLines.push(mergedLine);
    }
  }

  // 4️⃣ Reconstruct document layout flow
  const finalHtmlBlocks: string[] = [];
  let inList = false;

  for (const line of finalLines) {
    const mergedPlainText = line.map(p => p.html.replace(/<[^>]*>/g, "").trim()).join(" ");
    const isBullet = line.some(p => /^[•\-\▪]/.test(p.html.replace(/<[^>]*>/g, "").trim()));
    const maxFontSize = Math.max(...line.map(p => p.fontSize));
    
    // Check if line represents a heading
    const isHeading = maxFontSize > 18 || 
      (line.length === 1 && line[0].isBold && mergedPlainText.toUpperCase() === mergedPlainText && mergedPlainText.length < 60);

    if (isBullet) {
      if (!inList) {
        finalHtmlBlocks.push('<ul style="margin-top: 4px; margin-bottom: 4px; padding-left: 20px;">');
        inList = true;
      }
      
      const cleanLineContent = line.map(p => {
        let text = p.html;
        // Strip bullet characters from start of HTML
        text = text.replace(/^[•\-\▪]\s*/, "");
        // Also strip bullet characters that might be inside inner tags (like <b>•</b>)
        text = text.replace(/<[^>]*>[•\-\▪]<\/[^>]*>\s*/, "");
        return `<span class="${p.className}" style="${p.style}">${text}</span>`;
      }).join(" ");

      finalHtmlBlocks.push(`  <li style="margin-bottom: 2px;">${cleanLineContent}</li>`);
    } else {
      if (inList) {
        finalHtmlBlocks.push("</ul>");
        inList = false;
      }

      if (line.length === 1) {
        const p = line[0];
        if (isHeading) {
          finalHtmlBlocks.push(`<h3 class="${p.className}" style="${p.style} margin-top: 12px; margin-bottom: 6px;">${p.html}</h3>`);
        } else {
          finalHtmlBlocks.push(`<p class="${p.className}" style="${p.style} margin-bottom: 6px;">${p.html}</p>`);
        }
      } else {
        // Multi-element row (e.g. key-value, job title + dates)
        // Convert to borderless table row to preserve layout alignment
        const tableHtml = [
          '<table style="width: 100%; border-collapse: collapse; margin-top: 2px; margin-bottom: 4px; table-layout: auto;" border="0">',
          '  <tbody>',
          '    <tr>'
        ];
        
        const colWidth = Math.floor(100 / line.length);
        line.forEach((p, idx) => {
          const textAlign = idx === line.length - 1 ? 'right' : 'left';
          tableHtml.push(`      <td style="width: ${colWidth}%; text-align: ${textAlign}; vertical-align: top; border: none; padding: 0; word-break: break-word; overflow-wrap: break-word;" class="${p.className}">`);
          tableHtml.push(`        <span style="${p.style}">${p.html}</span>`);
          tableHtml.push('      </td>');
        });
        
        tableHtml.push('    </tr>');
        tableHtml.push('  </tbody>');
        tableHtml.push('</table>');
        
        finalHtmlBlocks.push(tableHtml.join("\n"));
      }
    }
  }

  if (inList) {
    finalHtmlBlocks.push("</ul>");
  }

  return finalHtmlBlocks.join("\n");
}
