name: 'Database CI/CD with Portainer'

on: 
  push: 
    branches:
      - 'release-db/**'

jobs: 
  deploy: 
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'
 
      - name: 'Portainer Deploy'
        uses: 'cssnr/portainer-stack-deploy-action@v1'
        timeout-minutes: 15
        with:
          name: 'resumebuilder-db'
          type: 'file'
          file: 'Backend/docker-compose.db.yml'
          url: '${{ secrets.PORTAINER_HOST }}'
          token: '${{ secrets.PORTAINER_TOKEN }}'
          ref: "" 
          standalone: true
          prune: true
          pull: true
          env_data: |
            {
               "POSTGRES_USER": "${{ secrets.POSTGRES_USER }}",
               "POSTGRES_PASSWORD": "${{ secrets.POSTGRES_PASSWORD }}",
               "POSTGRES_DB": "${{ secrets.POSTGRES_DB }}"
            }
